"""Single source of truth for dialogue, voices and the event sequence of "ANGER".

`LINES` holds every spoken line. `SEQ` is the ordered list of events that audio/timeline.py
walks to produce build/timeline.json with absolute times (same event forms as before):
    ("scene", id) | ("beat", name[, offset]) | ("wait", s) | ("line", id[, overlap])
    ("line_at", id, offset) | ("music", cue, kw) | ("music_hold", cue) | ("sfx", name, kw)
Footsteps and other motion-locked sounds are reported by the scene modules themselves
(anim/scenes/*.sfx_events) and merged by the build, so they always land on the animation.
"""

VOICES = {
    "anger": {"voice": "am_onyx", "speed": 0.9, "lang": "en-us"},     # deep, slow, stoic
    "voice": {"voice": "am_santa", "speed": 1.0, "lang": "en-us"},    # the hermit in the dark
}

# id: (character, display text, tts text or None, speed override or None)
LINES = {
    # ---- S4: the depths
    "m01": ("voice", "You gotta watch out for those things. They'll make you their lunch.", None, None),
    "m02": ("voice", "But I'm gonna make it MY lunch now.", "But I'm gonna make it my lunch now.", 0.95),
    # ---- S5: the voice
    "a01": ("anger", "Who are you? How did you get here?", None, 0.9),
    "m03": ("voice", "The food was good... but now a nap sounds even better.", None, 0.95),
    "a02": ("anger", "How did I get myself into this...", "How did I get myself into this...", 0.85),
    # ---- S6: the friend
    "a03": ("anger", "What the hell are you?", None, 0.95),
    "m04": ("voice", "That's my friend. He's saying hi. I think he likes you.", None, None),
    "a04": ("anger", "Tell your friend to give me a little space. Please.", None, 0.9),
    "m05": ("voice", "Hey, he can hear you, buddy. Treat him with some respect. We go way back, okay?", None, None),
    "a05": ("anger", "Well. How are you guys gonna get out of here?", None, 0.92),
    "m06": ("voice", "(laughs for way too long)", None, None),          # composed laugh, see audio/tts.py
    "m07": ("voice", "We would've gotten out of here a long time ago if we could have. "
                     "But now it seems you're stuck in here with us. How do you feel about that?", None, None),
    "a06": ("anger", "Well... I guess I'll die then.", "Well. I guess I'll die then.", 0.85),
}

# Lines rendered by a custom builder instead of a single TTS call (audio/tts.py COMPOSED)
COMPOSED = {"m06"}
WHISPER = {}
BREATHY = {"a02": 0.35}

# Music cue lengths (seconds); audio/music.py renders each to exactly this length.
# Filled from the timeline's beats (see BIBLE.md "Music").
MUSIC_CUES = {
    "descent": 39.0,
    "cavern": 21.2,
    "tension": 9.2,
    "fall": 17.6,
    "depths": 19.0,
    "menace": 8.1,
    "hermit": 8.09,
    "lull": 19.52,
    "friend": 55.77,
    "endcard": 5.0,
}

SEQ = [
    # ================= S1: the approach (opens straight on the torch flame - never on black)
    ("scene", "s1"),
    ("music", "descent", {"gain_db": -3.0, "end_beat": "reveal_settle"}),
    ("sfx", "cave_air_loop", {"gain_db": -22.0, "end_beat": "torch_splash"}),
    ("sfx", "torch_loop", {"gain_db": -17.0, "end_beat": "torch_splash"}),
    ("beat", "title_in", 0.8),
    ("beat", "title_out", 6.4),
    ("beat", "walk_start", 4.0),
    ("beat", "vines", 13.5),
    ("beat", "chop1", 14.8),
    ("sfx", "sword_chop", {"offset": 14.8, "gain_db": -6.0}),
    ("beat", "chop2", 16.0),
    ("sfx", "sword_chop", {"offset": 16.0, "gain_db": -6.0}),
    ("beat", "chop3", 17.2),
    ("sfx", "sword_chop", {"offset": 17.2, "gain_db": -5.0}),
    ("sfx", "vines_fall", {"offset": 17.4, "gain_db": -10.0}),
    ("beat", "webs", 19.6),
    ("beat", "web_swipe1", 20.6),
    ("sfx", "web_tear", {"offset": 20.6, "gain_db": -10.0}),
    ("beat", "web_swipe2", 21.9),
    ("sfx", "web_tear", {"offset": 21.9, "gain_db": -10.0}),
    ("beat", "door_arrive", 24.6),
    ("beat", "door_try1", 26.0),
    ("sfx", "door_locked", {"offset": 26.0, "gain_db": -7.0}),
    ("beat", "door_try2", 27.5),
    ("sfx", "door_locked", {"offset": 27.5, "gain_db": -5.0}),
    ("beat", "back_up", 29.0),
    ("beat", "charge", 31.4),
    ("beat", "door_burst", 33.0),
    ("sfx", "door_explode", {"offset": 33.0, "gain_db": -1.0}),
    ("sfx", "debris_rain", {"offset": 33.3, "gain_db": -10.0}),
    ("wait", 36.5),

    # ================= S2: the cavern
    ("scene", "s2"),
    ("beat", "reveal", 0.0),
    ("beat", "reveal_settle", 2.5),
    ("music", "cavern", {"gain_db": -4.0, "fade_in": 0.6, "end_beat": "torch_splash"}),
    ("beat", "look_around", 3.0),
    ("beat", "search_start", 7.5),
    ("beat", "eyes_glow", 12.0),
    ("beat", "eyes_scurry", 13.3),
    ("sfx", "scurry", {"offset": 13.3, "gain_db": -20.0}),
    ("beat", "stone_shift", 19.5),
    ("sfx", "stone_shift", {"offset": 19.5, "gain_db": -6.0}),
    ("beat", "torch_fly", 19.9),
    ("sfx", "torch_whoosh", {"offset": 19.9, "gain_db": -10.0}),
    ("beat", "torch_splash", 21.2),
    ("sfx", "torch_splash", {"offset": 21.2, "gain_db": -4.0}),
    ("beat", "torch_out", 21.6),
    ("sfx", "drip", {"offset": 23.4, "gain_db": -18.0}),
    ("beat", "listen", 23.0),
    ("sfx", "drip", {"offset": 25.9, "gain_db": -20.0}),
    ("sfx", "drip", {"offset": 27.6, "gain_db": -19.0}),
    ("beat", "scurry_behind", 28.4),
    ("sfx", "scurry", {"offset": 28.4, "gain_db": -15.0}),
    ("beat", "over_shoulder", 29.4),
    ("sfx", "drip", {"offset": 31.2, "gain_db": -20.0}),
    ("beat", "continue", 32.6),
    ("beat", "tension_start", 32.6),
    ("wait", 32.6),
    ("music", "tension", {"gain_db": -8.0, "end_beat": "collapse"}),
    ("wait", 7.4),

    # ================= S3: the fall
    ("scene", "s3"),
    ("beat", "wrong_rock", 1.2),
    ("sfx", "rock_crack", {"offset": 1.2, "gain_db": -6.0}),
    ("beat", "collapse", 1.8),
    ("sfx", "floor_collapse", {"offset": 1.8, "gain_db": -2.0}),
    ("beat", "fall_music", 1.8),
    ("beat", "grab_ledge", 2.8),
    ("sfx", "armor_clank", {"offset": 2.8, "gain_db": -6.0}),
    ("beat", "slipping", 4.5),
    ("sfx", "dust_slip", {"offset": 4.5, "gain_db": -12.0}),
    ("beat", "let_go", 8.6),
    ("beat", "falling", 8.8),
    ("beat", "sword_thrust", 12.6),
    ("sfx", "sword_stab", {"offset": 12.6, "gain_db": -3.0}),
    ("sfx", "sword_scrape", {"offset": 12.75, "gain_db": -6.0}),
    ("beat", "impact", 17.4),
    ("sfx", "heavy_impact", {"offset": 17.4, "gain_db": 0.0}),
    ("sfx", "armor_clatter", {"offset": 17.5, "gain_db": -8.0}),
    ("wait", 1.8),
    ("music", "fall", {"gain_db": -3.0, "end_beat": "fall_end"}),
    ("wait", 17.6),
    ("beat", "fall_end", 0.0),
    ("wait", 0.6),

    # ================= S4: the depths
    ("scene", "s4"),
    ("music", "depths", {"gain_db": -8.0, "fade_in": 2.0, "end_beat": "monster_approach"}),
    ("sfx", "deep_air_loop", {"gain_db": -24.0, "end_beat": "end"}),
    ("beat", "dazed", 0.4),
    ("sfx", "anger_groan", {"offset": 1.6, "gain_db": -6.0}),
    ("beat", "assess", 3.0),
    ("beat", "eyes_again", 9.0),
    ("sfx", "scurry", {"offset": 9.6, "gain_db": -16.0}),
    ("beat", "pass_out", 12.0),
    ("beat", "wake_noise", 15.4),
    ("sfx", "pebbles_shift", {"offset": 15.4, "gain_db": -10.0}),
    ("beat", "one_arm", 17.4),
    ("beat", "monster_approach", 19.0),
    ("sfx", "monster_growl", {"offset": 19.6, "gain_db": -10.0}),
    ("beat", "arm_up", 21.6),
    ("beat", "monster_reveal", 23.2),
    ("sfx", "monster_hiss", {"offset": 23.4, "gain_db": -6.0}),
    ("sfx", "drool_drip", {"offset": 24.6, "gain_db": -16.0}),
    ("beat", "monster_lunge", 26.6),
    ("sfx", "rock_whoosh", {"offset": 26.75, "gain_db": -10.0}),
    ("beat", "rock_hit", 27.1),
    ("sfx", "rock_bonk", {"offset": 27.1, "gain_db": -2.0}),
    ("sfx", "body_thud", {"offset": 27.55, "gain_db": -6.0}),
    ("wait", 19.0),
    ("music", "menace", {"gain_db": -4.0, "end_beat": "rock_hit"}),
    ("wait", 10.5),
    ("beat", "one_eye_open", -0.6),
    ("wait", 1.4),
    ("line", "m01"),
    ("wait", 0.45),
    ("beat", "hermit_start", -0.2),
    ("music", "hermit", {"gain_db": -10.0, "fade_out": 1.5, "end_beat": "crunch_end"}),
    ("line", "m02"),
    ("wait", 0.3),
    ("beat", "glove_grab"),
    ("sfx", "tail_grab", {"gain_db": -10.0}),
    ("sfx", "drag", {"offset": 0.35, "gain_db": -10.0}),
    ("wait", 2.0),
    ("beat", "crunch"),
    ("sfx", "crunching", {"gain_db": -6.0}),
    ("wait", 3.6),
    ("beat", "crunch_end"),
    ("wait", 0.6),

    # ================= S5: the voice
    ("scene", "s5"),
    ("beat", "prop_up", 0.3),
    ("sfx", "armor_scrape", {"offset": 0.5, "gain_db": -12.0}),
    ("wait", 3.4),
    ("line", "a01"),
    ("wait", 2.6),                       # silence
    ("line", "m03"),
    ("beat", "eye_roll", 0.3),
    ("wait", 1.2),
    ("beat", "snore_start"),
    ("sfx", "snore_loop", {"gain_db": -8.0, "end_beat": "startled"}),
    ("music", "lull", {"gain_db": -14.0, "fade_in": 2.0, "fade_out": 2.0, "end_beat": "startled"}),
    ("wait", 2.4),
    ("beat", "contemplate"),
    ("wait", 1.6),
    ("line", "a02"),
    ("wait", 1.8),
    ("beat", "close_eyes"),
    ("wait", 3.0),

    # ================= S6: the friend
    ("scene", "s6"),
    ("beat", "sleeping"),
    ("wait", 3.0),
    ("beat", "drip1"),
    ("sfx", "saliva_drip", {"gain_db": -10.0}),
    ("wait", 1.2),
    ("beat", "drip2"),
    ("sfx", "saliva_drip", {"gain_db": -9.0}),
    ("wait", 0.6),
    ("beat", "hand_wave"),
    ("wait", 1.2),
    ("beat", "side_eye_open"),
    ("wait", 1.5),
    ("beat", "sees_tongue"),
    ("wait", 1.0),
    ("beat", "startled"),
    ("sfx", "startle_sting", {"gain_db": -6.0}),
    ("music", "friend", {"gain_db": -9.0, "end_beat": "end_card"}),
    ("wait", 1.6),
    ("line", "a03"),
    ("wait", 0.7),
    ("line", "m04"),
    ("beat", "shift_away", 0.3),
    ("sfx", "armor_scrape", {"offset": 0.4, "gain_db": -14.0}),
    ("wait", 1.2),
    ("line", "a04"),
    ("wait", 0.5),
    ("beat", "sass"),
    ("sfx", "creature_huff", {"gain_db": -8.0}),
    ("sfx", "stomp", {"offset": 0.9, "gain_db": -6.0}),
    ("sfx", "stomp", {"offset": 1.6, "gain_db": -6.0}),
    ("sfx", "stomp", {"offset": 2.3, "gain_db": -5.0}),
    ("wait", 3.0),
    ("line", "m05"),
    ("beat", "wipe_saliva", 0.3),
    ("wait", 1.0),
    ("beat", "awkward"),
    ("sfx", "foot_tap_heavy", {"offset": 0.8, "gain_db": -10.0}),
    ("wait", 6.0),
    ("line", "a05"),
    ("wait", 0.4),
    ("beat", "laugh_start"),
    ("line", "m06"),
    ("wait", 0.6),
    ("line", "m07"),
    ("wait", 1.2),
    ("line", "a06"),
    ("wait", 0.8),
    ("beat", "snort"),
    ("sfx", "creature_snort", {"gain_db": -6.0}),
    ("sfx", "creature_giggle", {"offset": 0.5, "gain_db": -8.0}),
    ("wait", 1.4),
    ("beat", "anger_smirk"),
    ("wait", 1.2),
    ("beat", "notices_smirk"),
    ("wait", 0.3),
    ("sfx", "anger_throat_clear", {"gain_db": -6.0}),
    ("wait", 0.8),
    ("beat", "serious", -0.3),
    ("wait", 2.2),
    ("beat", "end_card"),
    ("music", "endcard", {"gain_db": -6.0, "fade_out": 1.0}),
    ("wait", 5.0),
    ("beat", "end"),
]
