"""Single source of truth for dialogue, voices and the event sequence of "ANGER".

`LINES` holds every spoken line. `SEQ` is the ordered list of events that audio/timeline.py
walks to produce build/timeline.json with absolute times (same event forms as before):
    ("scene", id) | ("beat", name[, offset]) | ("wait", s) | ("line", id[, overlap])
    ("line_at", id, offset) | ("music", cue, kw) | ("music_hold", cue) | ("sfx", name, kw)
Footsteps and other motion-locked sounds are reported by the scene modules themselves
(anim/scenes/*.sfx_events) and merged by the build, so they always land on the animation.
"""

VOICES = {
    "anger": {"voice": "am_onyx", "speed": 0.85, "lang": "en-us"},    # deep, slow, stoic
    "voice": {"voice": "am_santa", "speed": 0.88, "lang": "en-us"},   # the hermit in the dark
    # the storyteller: an old British voice pitched down 3 semitones (deeper, slower, bigger) - a wizard
    # reading from a very old book. No lip-sync (never on screen).
    "narrator": {"voice": "bm_george", "speed": 1.0, "lang": "en-gb", "semis": -3.0, "lips": False},
}

# id: (character, display text, tts text or None, speed override or None)
# In tts text, "|" = a short pause between sentences, "||" = a long one (audio/tts.py speak()).
LINES = {
    # ---- S1: the approach (narration over the action)
    "n01": ("narrator", "Deep beneath the mountain, where the sun had never shone... walked a warrior named Anger.", None, None),
    "n02": ("narrator", "He was a man of very few words... and even fewer smiles.", None, None),
    "n03": ("narrator", "When vines blocked his path, he did not go around.", None, None),
    "n04": ("narrator", "Cobwebs, he swept aside with the back of his hand.", None, None),
    "n05": ("narrator", "At the end of the tunnel stood an old iron door.", None, None),
    "n06": ("narrator", "It was locked.", None, None),
    "n07": ("narrator", "Anger did not believe in locked doors.", None, None),
    "n08": ("narrator", "Only in open ones.", None, None),
    # ---- S2: the cavern
    "n09": ("narrator", "Beyond the door lay a cavern so vast, his torchlight could not find its walls.", None, None),
    "n10": ("narrator", "It was dark, and cold, and very, very quiet.", None, None),
    "n11": ("narrator", "He did not see the eyes. But the eyes... had seen him.",
            "He did not see the eyes. | But the eyes... had seen him.", None),
    "n12": ("narrator", "And then, there was only darkness.", None, None),
    "n13": ("narrator", "Anger stood perfectly still... and listened.", None, None),
    "n14": ("narrator", "Nothing. Nothing he could see.", "Nothing. | Nothing he could see.", None),
    "n15": ("narrator", "So he pressed on, sword raised... never noticing the thin cracks spreading beneath his feet.", None, None),
    # ---- S3: the fall
    "n16": ("narrator", "He caught the edge. But steel is heavy... and stone is unforgiving.",
            "He caught the edge. | But steel is heavy... and stone is unforgiving.", None),
    "n17": ("narrator", "Anger did not scream.", None, None),
    "n18": ("narrator", "He simply closed his eyes.", None, None),
    "n19": ("narrator", "His sword bit into the stone...", None, None),
    "n20": ("narrator", "...until it struck solid rock.", "until it struck solid rock.", None),
    # ---- S4: the depths
    "n21": ("narrator", "The sword had saved his life. But not his bones.",
            "The sword had saved his life. | But not his bones.", None),
    "n22": ("narrator", "And he was not alone.", None, None),
    "n23": ("narrator", "Then the darkness took him.", None, None),
    "n24": ("narrator", "When he woke... he could move only one arm.", None, None),
    "n25": ("narrator", "The creature had waited a very long time for a meal like this.", None, None),
    "n26": ("narrator", "Someone... had thrown that rock.", None, None),
    "m01": ("voice", "You gotta watch out for those things. They'll make you their lunch.",
            "You gotta watch out for those things. | They'll make you their lunch.", None),
    "m02": ("voice", "But I'm gonna make it MY lunch now.", "But I'm gonna make it my lunch now!", 0.92),
    "n27": ("narrator", "Anger had no idea how to feel about this.", None, None),
    # ---- S5: the voice
    "n28": ("narrator", "With great effort, Anger dragged himself up against the wall.", None, None),
    "a01": ("anger", "Who... are you? How did you get here?", "Who | are you? || How did you... get here?", 0.8),
    "m03": ("voice", "The food was good... but now a nap sounds even better.",
            "The food was good... | but now, a nap sounds even better.", 0.85),
    "n29": ("narrator", "Anger rolled his eyes.", None, None),
    "n30": ("narrator", "Within seconds, the stranger was snoring.", None, None),
    "n31": ("narrator", "Anger stared into the darkness, and wondered where his life had gone wrong.", None, None),
    "a02": ("anger", "How did I get myself into this...", "How did I get myself... into this...", 0.78),
    "n32": ("narrator", "Eventually, he gave up... and went to sleep.", None, None),
    # ---- S6: the friend
    "n33": ("narrator", "He did not sleep for long.", None, None),
    "n34": ("narrator", "Something warm... and wet... was dripping on his face.", None, None),
    "a03": ("anger", "What the hell are you?!", "What the hell... are you?!", 0.9),
    "m04": ("voice", "That's my friend. He's saying hi. I think he likes you.",
            "That's my friend. | He's saying hi. | I think he likes you.", None),
    "n35": ("narrator", "Anger shuffled out from under the drool.", None, None),
    "a04": ("anger", "Tell your friend to give me a little space. Please.",
            "Tell your friend to give me a little space. || Please.", 0.85),
    "n36": ("narrator", "The creature did not like that.", None, None),
    "m05": ("voice", "Hey, he can hear you, buddy. Treat him with some respect. We go way back, okay?",
            "Hey! He can hear you, buddy. | Treat him with some respect. | We go way back, okay?", 0.9),
    "n37": ("narrator", "Anger wiped the slobber from his face.", None, None),
    "n38": ("narrator", "No one said anything... for a very long time.", None, None),
    "a05": ("anger", "Well. How are you guys gonna get out of here?",
            "Well. || How are you guys gonna get out of here?", 0.85),
    "m06": ("voice", "(laughs for way too long)", None, None),          # composed laugh, see audio/tts.py
    "m07": ("voice", "We would've gotten out of here a long time ago if we could have. "
                     "But now it seems you're stuck in here with us. How do you feel about that?",
            "We would've gotten out of here a long time ago, if we could have. | "
            "But now it seems you're stuck in here with us. | How do you feel about that?", None),
    "a06": ("anger", "Well... I guess I'll die then.", "Well. || I guess I'll die then.", 0.8),
    "n39": ("narrator", "For one brief moment, Anger had almost smiled.", None, None),
    "n40": ("narrator", "And so began the strangest friendship the deep had ever known.", None, None),
}

# Lines rendered by a custom builder instead of a single TTS call (audio/tts.py COMPOSED)
COMPOSED = {"m06"}
WHISPER = {}
BREATHY = {}
# Emotional colouring per line (audio/tts.py mood()): Anger is badly hurt in S4-S5, weary after.
MOOD = {
    "a01": {"pre": "pain", "tremble": 0.12, "breathy": 0.3},          # hurt, every word costs him
    "m03": {"breathy": 0.15, "post": "sigh"},                         # full and sleepy
    "a02": {"breathy": 0.4, "tremble": 0.05, "post": "sigh"},         # muttered, weary
    "a03": {"pre": "gasp"},                                           # jolted awake
    "a04": {"pre": "breath"},                                         # strained patience
    "a05": {"pre": "breath"},
    "a06": {},                                                        # utterly flat
}

# Music cue lengths (seconds); audio/music.py renders each to exactly this length.
# Filled from the timeline's beats (see BIBLE.md "Music").
MUSIC_CUES = {
    "descent": 43.6,
    "cavern": 21.2,
    "tension": 9.2,
    "fall": 20.0,
    "depths": 22.184,
    "menace": 10.458,
    "hermit": 8.34,
    "lull": 32.866,
    "friend": 77.383,
    "endcard": 6.0,
}

SEQ = [
    # ================= S1: the approach (opens straight on the torch flame - never on black)
    # The narrator (rev 2) speaks over the action: each line lands just before or on what it describes.
    ("scene", "s1"),
    ("music", "descent", {"gain_db": -3.0, "end_beat": "reveal_settle"}),
    ("sfx", "cave_air_loop", {"gain_db": -22.0, "end_beat": "torch_splash"}),
    ("sfx", "torch_loop", {"gain_db": -17.0, "end_beat": "torch_splash"}),
    ("beat", "title_in", 0.8),
    ("line_at", "n01", 1.2),
    ("beat", "title_out", 6.4),
    ("beat", "walk_start", 4.0),
    ("line_at", "n02", 7.9),
    ("line_end_at", "n03", 17.2),
    ("beat", "vines", 15.9),
    ("beat", "chop1", 17.4),
    ("sfx", "sword_chop", {"offset": 17.4, "gain_db": -6.0}),
    ("beat", "chop2", 18.6),
    ("sfx", "sword_chop", {"offset": 18.6, "gain_db": -6.0}),
    ("beat", "chop3", 19.8),
    ("sfx", "sword_chop", {"offset": 19.8, "gain_db": -5.0}),
    ("sfx", "vines_fall", {"offset": 20.0, "gain_db": -10.0}),
    ("line_at", "n04", 20.4),
    ("beat", "webs", 23.2),
    ("beat", "web_swipe1", 24.2),
    ("sfx", "web_tear", {"offset": 24.2, "gain_db": -10.0}),
    ("beat", "web_swipe2", 25.5),
    ("sfx", "web_tear", {"offset": 25.5, "gain_db": -10.0}),
    ("line_at", "n05", 25.9),
    ("beat", "door_arrive", 28.4),
    ("beat", "door_try1", 29.8),
    ("sfx", "door_locked", {"offset": 29.8, "gain_db": -7.0}),
    ("beat", "door_try2", 31.3),
    ("sfx", "door_locked", {"offset": 31.3, "gain_db": -5.0}),
    ("line_at", "n06", 32.15),
    ("beat", "back_up", 33.6),
    ("line_at", "n07", 33.8),
    ("beat", "charge", 36.0),
    ("beat", "door_burst", 37.6),
    ("sfx", "door_explode", {"offset": 37.6, "gain_db": -1.0}),
    ("sfx", "debris_rain", {"offset": 37.9, "gain_db": -10.0}),
    ("line_at", "n08", 38.9),
    ("wait", 41.1),

    # ================= S2: the cavern
    ("scene", "s2"),
    ("beat", "reveal", 0.0),
    ("beat", "reveal_settle", 2.5),
    ("music", "cavern", {"gain_db": -4.0, "fade_in": 0.6, "end_beat": "torch_splash"}),
    ("line_at", "n09", 0.6),
    ("beat", "look_around", 3.0),
    ("line_at", "n10", 7.2),
    ("beat", "search_start", 7.5),
    ("beat", "eyes_glow", 12.0),
    ("beat", "eyes_scurry", 13.3),
    ("sfx", "scurry", {"offset": 13.3, "gain_db": -20.0}),
    ("line_at", "n11", 14.1),
    ("beat", "stone_shift", 19.5),
    ("sfx", "stone_shift", {"offset": 19.5, "gain_db": -6.0}),
    ("beat", "torch_fly", 19.9),
    ("sfx", "torch_whoosh", {"offset": 19.9, "gain_db": -10.0}),
    ("beat", "torch_splash", 21.2),
    ("sfx", "torch_splash", {"offset": 21.2, "gain_db": -4.0}),
    ("beat", "torch_out", 21.6),
    ("line_at", "n12", 22.2),
    ("sfx", "drip", {"offset": 23.4, "gain_db": -18.0}),
    ("beat", "listen", 23.0),
    ("line_at", "n13", 25.0),
    ("sfx", "drip", {"offset": 25.9, "gain_db": -20.0}),
    ("sfx", "drip", {"offset": 27.6, "gain_db": -19.0}),
    ("beat", "scurry_behind", 28.4),
    ("sfx", "scurry", {"offset": 28.4, "gain_db": -15.0}),
    ("beat", "over_shoulder", 29.4),
    ("line_at", "n14", 30.5),
    ("sfx", "drip", {"offset": 31.2, "gain_db": -20.0}),
    ("beat", "continue", 32.6),
    ("beat", "tension_start", 32.6),
    ("line_at", "n15", 34.0),           # "...never noticing the thin cracks": the floor shows cracks ahead of him
    ("beat", "cracks_seen", 37.2),      # the cracks are framed/legible from here (rev 2 foreshadowing)
    ("wait", 32.6),
    ("music", "tension", {"gain_db": -8.0, "end_beat": "collapse"}),
    ("wait", 7.4),

    # ================= S3: the fall
    ("scene", "s3"),
    ("beat", "wrong_rock", 1.2),
    ("sfx", "rock_crack", {"offset": 1.2, "gain_db": -6.0}),
    ("beat", "collapse", 1.8),
    ("sfx", "floor_collapse", {"offset": 1.8, "gain_db": -2.0}),
    ("beat", "fall_music", 1.8),
    ("beat", "grab_ledge", 2.8),
    ("sfx", "armor_clank", {"offset": 2.8, "gain_db": -6.0}),
    ("line_at", "n16", 3.1),
    ("beat", "slipping", 4.5),
    ("sfx", "dust_slip", {"offset": 4.5, "gain_db": -12.0}),
    ("beat", "let_go", 8.6),
    ("beat", "falling", 8.8),
    ("line_at", "n17", 9.2),
    ("line_at", "n18", 11.5),           # "He simply closed his eyes." - eyes close on it
    ("beat", "sword_thrust", 14.0),     # eyes SNAP open, sword into the wall
    ("sfx", "sword_stab", {"offset": 14.0, "gain_db": -3.0}),
    ("sfx", "sword_scrape", {"offset": 14.15, "gain_db": -8.0, "end_beat": "sword_clang"}),
    ("line_at", "n19", 14.35),
    ("line_at", "n20", 16.85),          # "...until it struck solid rock." - CLANG on "rock"
    ("beat", "sword_clang", 18.35),     # blade hits a vein of solid rock: stops dead, his grip tears loose
    ("sfx", "sword_clang", {"offset": 18.35, "gain_db": -3.0}),
    ("beat", "freefall", 18.5),         # falls the rest of the way, the sword left stuck above
    ("beat", "impact", 19.8),
    ("sfx", "heavy_impact", {"offset": 19.8, "gain_db": 0.0}),
    ("sfx", "armor_clatter", {"offset": 19.9, "gain_db": -8.0}),
    ("wait", 1.8),
    ("music", "fall", {"gain_db": -3.0, "end_beat": "fall_end"}),
    ("wait", 20.0),
    ("beat", "fall_end", 0.0),
    ("wait", 0.6),

    # ================= S4: the depths
    ("scene", "s4"),
    ("music", "depths", {"gain_db": -8.0, "fade_in": 2.0, "end_beat": "monster_approach"}),
    ("sfx", "deep_air_loop", {"gain_db": -24.0, "end_beat": "end"}),
    ("beat", "dazed", 0.4),
    ("sfx", "anger_groan", {"offset": 1.6, "gain_db": -6.0}),
    ("wait", 3.6),
    ("beat", "assess"),
    ("line", "n21"),
    ("wait", 0.9),
    ("beat", "eyes_again"),
    ("sfx", "scurry", {"offset": 0.6, "gain_db": -16.0}),
    ("line_at", "n22", 1.4),
    ("wait", 4.2),
    ("beat", "pass_out"),
    ("line_at", "n23", 0.5),
    ("wait", 4.0),
    ("beat", "wake_noise"),
    ("sfx", "pebbles_shift", {"gain_db": -6.0}),
    ("wait", 1.6),
    ("beat", "one_arm"),
    ("line", "n24"),
    ("wait", 0.5),
    ("beat", "monster_approach"),
    ("sfx", "monster_growl", {"offset": 0.6, "gain_db": -10.0}),
    ("music", "menace", {"gain_db": -4.0, "end_beat": "rock_hit"}),
    ("wait", 0.8),
    ("line", "n25"),
    ("beat", "arm_up", -1.2),
    ("wait", 0.8),
    ("beat", "monster_reveal"),
    ("sfx", "monster_hiss", {"offset": 0.2, "gain_db": -6.0}),
    ("sfx", "drool_drip", {"offset": 1.4, "gain_db": -10.0}),
    ("wait", 3.4),
    ("beat", "monster_lunge"),
    ("sfx", "rock_whoosh", {"offset": 0.15, "gain_db": -10.0}),
    ("wait", 0.5),
    ("beat", "rock_hit"),
    ("sfx", "rock_bonk", {"gain_db": -2.0}),
    ("sfx", "body_thud", {"offset": 0.45, "gain_db": -6.0}),
    ("wait", 2.3),
    ("beat", "one_eye_open"),
    ("wait", 1.0),
    ("line", "n26"),
    ("wait", 0.7),
    ("line", "m01"),
    ("wait", 0.7),
    ("beat", "hermit_start", -0.2),
    ("music", "hermit", {"gain_db": -10.0, "fade_out": 1.5, "end_beat": "crunch_end"}),
    ("line", "m02"),
    ("wait", 0.5),
    ("beat", "glove_grab"),
    ("sfx", "tail_grab", {"gain_db": -10.0}),
    ("sfx", "drag", {"offset": 0.35, "gain_db": -10.0}),
    ("wait", 2.0),
    ("beat", "crunch"),
    ("sfx", "crunching", {"gain_db": -9.0}),
    ("line_at", "n27", 0.5),             # "Anger had no idea how to feel about this." over the crunching
    ("wait", 3.6),
    ("beat", "crunch_end"),
    ("wait", 0.8),

    # ================= S5: the voice
    ("scene", "s5"),
    ("beat", "prop_up", 0.3),
    ("sfx", "armor_scrape", {"offset": 0.5, "gain_db": -12.0}),
    ("line_at", "n28", 0.3),
    ("wait", 5.0),
    ("line", "a01"),
    ("wait", 2.6),                       # silence
    ("line", "m03"),
    ("wait", 0.5),
    ("line", "n29"),                     # "Anger rolled his eyes."
    ("beat", "eye_roll", -0.4),
    ("wait", 1.4),
    ("beat", "snore_start"),
    ("sfx", "snore_loop", {"gain_db": -11.0, "end_beat": "startled"}),
    ("music", "lull", {"gain_db": -14.0, "fade_in": 2.0, "fade_out": 2.0, "end_beat": "startled"}),
    ("wait", 1.2),
    ("line", "n30"),
    ("wait", 0.5),
    ("beat", "contemplate"),
    ("line", "n31"),
    ("wait", 0.6),
    ("line", "a02"),
    ("wait", 1.0),
    ("line", "n32"),
    ("beat", "close_eyes", -1.6),
    ("wait", 1.5),

    # ================= S6: the friend
    ("scene", "s6"),
    ("beat", "sleeping"),
    ("line_at", "n33", 0.6),
    ("wait", 2.9),
    ("beat", "drip1"),
    ("sfx", "saliva_drip", {"gain_db": -10.0}),
    ("wait", 1.2),
    ("beat", "drip2"),
    ("sfx", "saliva_drip", {"gain_db": -9.0}),
    ("wait", 0.6),
    ("beat", "hand_wave"),
    ("wait", 0.9),
    ("line", "n34"),
    ("wait", 0.3),
    ("beat", "side_eye_open"),
    ("wait", 1.5),
    ("beat", "sees_tongue"),
    ("wait", 1.0),
    ("beat", "startled"),
    ("sfx", "startle_sting", {"gain_db": -6.0}),
    ("music", "friend", {"gain_db": -9.0, "end_beat": "end_card"}),
    ("wait", 1.3),
    ("line", "a03"),
    ("wait", 0.8),
    ("line", "m04"),
    ("wait", 0.5),
    ("line", "n35"),                     # "Anger shuffled out from under the drool."
    ("beat", "shift_away", -2.2),
    ("sfx", "armor_scrape", {"offset": -2.1, "gain_db": -14.0}),
    ("wait", 0.6),
    ("line", "a04"),
    ("wait", 0.7),
    ("line", "n36"),                     # "The creature did not like that."
    ("wait", 0.1),
    ("beat", "sass"),
    ("sfx", "creature_huff", {"gain_db": -8.0}),
    ("sfx", "stomp", {"offset": 0.9, "gain_db": -6.0}),
    ("sfx", "stomp", {"offset": 1.6, "gain_db": -6.0}),
    ("sfx", "stomp", {"offset": 2.3, "gain_db": -6.0}),
    ("sfx", "stomp", {"offset": 3.0, "gain_db": -5.0}),
    ("wait", 3.8),
    ("line", "m05"),
    ("wait", 0.4),
    ("line", "n37"),                     # "Anger wiped the slobber from his face."
    ("beat", "wipe_saliva", -2.2),
    ("wait", 0.8),
    ("beat", "awkward"),
    ("sfx", "foot_tap_heavy", {"offset": 0.8, "gain_db": -10.0}),
    ("line_at", "n38", 2.2),             # "No one said anything... for a very long time."
    ("wait", 6.6),
    ("line", "a05"),
    ("wait", 0.5),
    ("beat", "laugh_start"),
    ("line", "m06"),
    ("wait", 0.6),
    ("line", "m07"),
    ("wait", 1.2),
    ("line", "a06"),
    ("wait", 0.8),
    ("beat", "snort"),
    ("sfx", "creature_snort", {"gain_db": -6.0}),
    ("sfx", "creature_giggle", {"offset": 0.5, "gain_db": -8.0}),
    ("wait", 1.4),
    ("beat", "anger_smirk"),
    ("wait", 1.2),
    ("beat", "notices_smirk"),
    ("wait", 0.3),
    ("sfx", "anger_throat_clear", {"gain_db": -6.0}),
    ("wait", 0.8),
    ("beat", "serious", -0.3),
    ("wait", 0.6),
    ("line", "n39"),                     # "For one brief moment, Anger had almost smiled."
    ("wait", 0.6),
    ("beat", "end_card"),
    ("music", "endcard", {"gain_db": -6.0, "fade_out": 1.0}),
    ("line_at", "n40", 0.3),
    ("wait", 6.0),
    ("beat", "end"),
]
