"""PART 3 — THE LONG GAME"""
from toon.engine import Part
from toon.sets import ROW_Y, SEAT_OFF
from story.common import title, text_card, stage_duo, stands_trio, STAGE_Y

ROW1 = ROW_Y[1] + SEAT_OFF
ROW2 = ROW_Y[2] + SEAT_OFF


def build():
    P = Part(3, "THE LONG GAME", "part3-the-long-game")
    title(P, 3, "THE LONG GAME")

    # ------------------------------------------------------------------ weeks later: the star (or so he thinks)
    s = P.shot("stage", mood="laugh", banner2="ASSEMBLY #4")
    s.music("assembly", gain=0.4, fade=0.2)
    s.overlay("label", at=0.1, dur=2.2, text=["WEEKS LATER"], x=540, y=580, size=56)
    pc, ch = stage_duo(s, pc_x=220, chad_x=860, pc=dict(eyes="happy", mouth="grin", arms="up", shades=1),
                       chad=dict(eyes="happy", mouth="grin", arms="up"))
    for a, ph in ((pc, 0), (ch, 0.25)):
        for k in range(14):
            a.to(k * 0.5 + ph, 0.25, "out", hop=16)
            a.to(k * 0.5 + ph + 0.25, 0.25, "in", hop=0)
    c = s.actor("cartman", x=540, y=STAGE_Y, scale=1.0, eyes="half", mouth="smirk", arms="mic", hold="mic", puff=1,
                sparkle=1, z=1)
    s.camera(cx=540, cy=880, zoom=1.1)
    s.sfx("crowd_laugh", gain=0.5, d=3.0)
    s.narr("Weeks later, Cartman was the star of every emotional assembly. Or so he believed.")
    s.say(c, "You're welcome, everybody.", arms="out", hold=None, eyes="closed", mouth="smirk")
    s.sfx("applause", gain=0.5, d=2.0)
    s.wait(0.3)
    s.end()

    # ------------------------------------------------------------------ the flop
    s = P.shot("stage", mood="bored", banner2="ASSEMBLY #7")
    pc, ch = stage_duo(s, pc_x=220, chad_x=860, pc=dict(eyes="open", mouth="smile", arms="hips", shades=1),
                       chad=dict(eyes="warm", mouth="smile", arms="cross"))
    c = s.actor("cartman", x=540, y=STAGE_Y, scale=1.0, eyes="half", mouth="smirk", arms="mic", hold="mic", puff=1,
                z=1)
    s.camera(cx=540, cy=880, zoom=1.15)
    s.say(c, "So, feelings. What's the deal with feelings, am I right?", gest=1.0, gap=0.3)
    s.music(None, fade=0.2)
    s.sfx("crickets", gain=0.9, d=2.6)
    s.cc("[Crickets]", dur=2.0)
    s.wait(2.0)
    s.say(c, "Feelings? Anyone?", eyes="open", mouth="smile", brow=0.6, puff=0.6, gap=0.2)
    s.sfx("cough", gain=0.8)
    s.cc("[Somebody coughs]", dur=1.0)
    s.wait(1.0)
    s.camera(dur=0.4, cx=540, cy=760, zoom=2.0)
    c.to(s.t, 0.4, puff=0, sweat=2, shiver=0.4, mouth="wobbly", eyes="wide")
    s.wait(0.4)
    s.think(c, "Oh no. Oh no, no, no. It's not landing. My humor isn't working on this crowd.", icon="!!!")
    s.think(c, "And these two dweebs can't save me. They aren't funny either. I'm doomed!", icon="X_X",
            eyes="squeeze", arms="face", hold=None)
    s.end()

    # ------------------------------------------------------------------ "now?" "now."
    s = P.shot("stage", mood="bored", banner2="ASSEMBLY #7")
    pc, ch = stage_duo(s, pc_x=220, chad_x=860, pc=dict(eyes="open", mouth="flat", arms="hips", shades=1, look=1),
                       chad=dict(eyes="half", mouth="smirk", arms="cross", look=-1))
    c = s.actor("cartman", x=540, y=STAGE_Y, scale=1.0, eyes="squeeze", mouth="wobbly", arms="face", sweat=2,
                shiver=0.4, z=0)
    s.camera(cx=540, cy=800, zoom=1.3)
    s.overlay("glance", at=0.1, dur=2.6, a=pc, b=ch, dy1=150, dy2=150)
    s.say(ch, "Now?", style="whisper", pre=0.3, gap=0.15)
    s.say(pc, "Now.", style="whisper", mouth="smirk", gap=0.3)
    pc.to(s.t, 0.4, shades=0.0, holdshades=0, eyes="half", look=0, mouth="smirk")
    ch.to(s.t, 0.4, look=0, arms="hips")
    s.sfx("sparkle", gain=0.5)
    s.wait(0.6)
    s.end()

    # ------------------------------------------------------------------ the five stages of grief
    s = P.shot("stage", mood="idle", banner2="ASSEMBLY #7", toilet=1, toilet_x=860)
    s.music("comedy", gain=0.25, fade=0.2)
    pc, ch = stage_duo(s, pc_x=250, chad_x=700, pc=dict(eyes="open", mouth="smile", arms="present", shades=0),
                       chad=dict(eyes="open", mouth="smile", arms="down", hold="phone"))
    c = s.actor("cartman", x=60, y=STAGE_Y, scale=1.0, eyes="wide", mouth="o", arms="down", sweat=1, z=-1)
    s.camera(cx=520, cy=860, zoom=1.1)
    s.say(pc, "Chad. The five stages of grief.", arms="present")
    s.say(ch, "After dropping your phone in the toilet.", arms="phone")
    ch.to(s.t, 0.3, arms="down", hold=None)
    s.sfx("pop", gain=0.6)
    s.overlay("sfx", dur=0.8, text="*PLOP*", x=860, y=880, size=80, color="#9fd8ff")
    s.wait(0.35)
    s.say(pc, "Stage one: Denial.", arms="point")
    ch.to(s.t, 0.3, x=760, look=0.9, looky=0.8, eyes="half")
    s.say(ch, "That's not my phone. My phone is in my pocket.", mouth="smile", arms="hips")
    s.param(mood="laugh")
    s.sfx("crowd_laugh", gain=0.5, d=2.2)
    s.wait(0.5)
    s.say(pc, "Stage two: Anger.")
    s.say(ch, "WHO DESIGNED A TOILET THIS PHONE-SHAPED?!", style="shout", eyes="angry", brow=-1, mouth="scream",
          arms="fists", look=0, looky=0)
    s.camera(at=s.t - 1.5, dur=0.2, shake=8)
    s.camera(at=s.t - 0.8, dur=0.3, shake=0)
    s.sfx("crowd_laugh", gain=0.7, d=2.6)
    s.wait(0.35)
    s.say(pc, "Stage three: Bargaining.")
    s.say(ch, "Rice. I'll put it in rice. I'll put my whole life in rice.", eyes="wide", brow=1, mouth="grimace",
          arms="rub", rub=1)
    ch.set(s.t, rub=0)
    s.sfx("crowd_laugh", gain=0.7, d=2.6)
    s.wait(0.35)
    s.say(pc, "Stage four: Depression.")
    ch.to(s.t, 0.4, rot=-1.5, y=STAGE_Y + 185, arms="face", eyes="teary", tears=0.8, brow=1)
    s.say(ch, "I'll never see my four thousand screenshots again.", mouth="wobbly", pre=0.4)
    s.param(mood="roar")
    s.sfx("crowd_laugh", gain=0.8, d=3.0)
    s.wait(0.35)
    s.say(pc, "Stage five: Acceptance.")
    ch.to(s.t, 0.4, rot=0.0, y=STAGE_Y, arms="down", eyes="closed", tears=0, brow=0, mouth="smile")
    s.wait(0.6)
    s.say(ch, "I'm a landline guy now.", speed=0.9, gap=0.1)
    s.sfx("badum", gain=0.7)
    s.sfx("crowd_laugh", gain=1.0, d=4.0)
    s.sfx("applause_big", at=s.t + 0.3, gain=0.6)
    s.param(mood="roar")
    s.camera(dur=0.6, cx=300, cy=760, zoom=1.6)
    c.to(s.t, 0.3, x=130, look=1, mouth="o", eyes="wide")
    s.cc("[The crowd goes wild]", dur=1.8)
    s.wait(1.8)
    s.end()

    # ------------------------------------------------------------------ the reveal
    s = P.shot("stage", mood="laugh", banner2="ASSEMBLY #7")
    s.music("warm", gain=0.3, fade=0.4)
    pc, ch = stage_duo(s, pc_x=330, chad_x=760, pc=dict(eyes="warm", mouth="smile", arms="hips", shades=0),
                       chad=dict(eyes="warm", mouth="smile", arms="heart", facing=-1))
    c = s.actor("cartman", x=540, y=STAGE_Y, scale=1.0, eyes="wide", mouth="o", arms="down", z=1, sweat=1)
    s.camera(cx=540, cy=840, zoom=1.45)
    s.say(ch, "We've always been funny, bro. We were toning it down so you could shine.", speed=0.95)
    s.say(pc, "Bringing you up was the whole point.", look=0.7)
    s.music(None, fade=0.1)
    c.to(s.t, 0.3, eyes="angry", brow=-1, mouth="scream", arms="fists", shiver=0.3)
    s.camera(dur=0.3, cx=540, cy=820, zoom=2.0)
    s.wait(0.3)
    s.say(c, "You were FUNNY this whole time?! You TRICKED me! You let me think you were dweebs!", style="shout")
    s.say(pc, "Dude, it wasn't a trick, it was-", brow=1, mouth="frown", arms="shrug", gap=0.0)
    s.say(c, "I don't need you! I'll do my own show! A SOLO show!", style="shout", arms="point")
    c.set(s.t, walk=1, facing=-1)
    c.to(s.t, 1.1, "in", x=-300)
    s.camera(dur=0.6, cx=540, cy=840, zoom=1.3)
    s.wait(1.1)
    s.end()

    # ------------------------------------------------------------------ the solo act
    s = P.shot("stage", mood="laugh", banner="CARTMAN: SOLO", banner2="ONE NIGHT ONLY", spot_x=540)
    s.music("sad", gain=0.4, fade=1.5)
    c = s.actor("cartman", x=540, y=STAGE_Y, scale=1.05, eyes="happy", mouth="grin", arms="mic", hold="mic",
                gest=1.0)
    s.overlay("vignette", at=0, dur=30, strength=0.5)
    s.camera(cx=540, cy=880, zoom=1.15)
    s.sfx("crowd_laugh", gain=0.55, d=2.4)
    s.sfx("applause", at=0.5, gain=0.35, d=2.0)
    s.cc("[Laughter]", dur=1.6)
    s.say(c, "Thank you! I'm here all week!", pre=0.4, arms="out", hold=None)
    s.narr("The solo shows went all right. He got laughs.")
    c.to(s.t - 1.0, 0.8, mouth="flat", eyes="half")
    s.camera(dur=8, ease="lin", cx=540, cy=760, zoom=1.7)
    s.narr("But for some reason he couldn't explain, it felt a little empty. Not nearly as fun as showing "
           "those two dweebs how cool he was.")
    s.param(mood="idle")
    s.think(c, "They're laughing. So why does this feel so... meh?", icon="meh", eyes="sad", brow=0.8,
            mouth="frown", arms="sad")
    s.end()

    # ------------------------------------------------------------------ the hallway, after a show
    s = P.shot("hallway", night=1, board=0, door_x=640, door=0.12)
    c = s.actor("cartman", x=-150, y=1560, scale=1.15, eyes="half", mouth="frown", arms="sad", walk=0.6, bob=0)
    c.to(0, 3.0, "lin", x=330)
    c.set(3.0, walk=0)
    s.camera(cx=540, cy=1050, zoom=1.15)
    s.wait(0.6)
    s.think(c, "That's it. I quit. Comedy is stupid. Everything is stupid.", icon="ugh")
    s.wait(0.2)
    c.to(s.t, 0.3, look=1, eyes="open", brow=0.3)
    s.cc("[The principal's door is open a crack]", dur=2.0)
    s.camera(dur=1.0, cx=700, cy=1000, zoom=1.4)
    s.wait(0.9)
    c.set(s.t, walk=0.6)
    c.to(s.t, 1.0, x=560)
    c.set(s.t + 1.0, walk=0, arms="reach")
    s.param(at=s.t + 1.0, dur=1.0, door=0.55)
    s.sfx("creak", at=s.t + 1.0, gain=0.8)
    s.wait(1.7)
    s.think(c, "Oh great. Here it comes.", icon="...", eyes="half", arms="sad")
    s.end()

    # ------------------------------------------------------------------ what he imagines
    s = P.shot("imagine")
    s.music("tension", gain=0.3, fade=0.3)
    pc = s.actor("pc", x=330, y=1450, scale=1.05, eyes="angry", brow=-1, mouth="smirk", shades=0, arms="cross")
    ch = s.actor("chad", x=760, y=1450, scale=1.05, eyes="angry", brow=-1, mouth="smirk", arms="hips")
    slug = s.actor("slug", x=560, y=1520, scale=0.9, mouth="frown", z=1)
    slug.to(0, 8, "lin", x=500)
    s.camera(cx=540, cy=1000, zoom=1.0)
    s.cc("[What Cartman imagines]", dur=1.6)
    s.say(pc, "Well, well, well. Look who's crawling back.", pitch=0.85, pre=0.2)
    s.say(ch, "Crawling back like a little slug, huh?", pitch=0.85)
    s.say(slug, "Squish.", voice="cartman", pitch=0.9, mouth="frown")
    s.end()

    # ------------------------------------------------------------------ what actually happens
    s = P.shot("office", night=1, door=0.55)
    s.music("warm", gain=0.35, fade=0.6)
    pc = s.actor("pc", x=250, y=1470, scale=1.1, eyes="open", mouth="smile", shades=0, arms="hips")
    ch = s.actor("chad", x=560, y=1470, scale=1.1, eyes="warm", mouth="smile", arms="down")
    c = s.actor("cartman", x=900, y=1480, scale=1.15, eyes="half", mouth="frown", arms="sad", z=1)
    s.camera(cx=560, cy=1060, zoom=1.08)
    ch.to(0.2, 0.25, "out", hop=40, eyes="happy", mouth="grin", arms="up")
    ch.to(0.45, 0.25, "in", hop=0)
    s.say(ch, "CARTMAN! Bro! You came!")
    s.say(pc, "Dude! We caught your solo show. Real chops.", arms="present")
    s.say(c, "You're not going to rub it in?", eyes="open", brow=0.6, mouth="flat")
    s.say(pc, "Rub what in? It's not about winning or losing, dude.", arms="shrug")
    s.say(ch, "We just want to have fun with you. And we want you to be as great as you can be.", arms="heart")
    s.say(c, "Even if I roast you? On stage?", eyes="half", mouth="smirk")
    pc.to(s.t, 0.3, look=0.9)
    ch.to(s.t, 0.3, look=-0.9)
    s.overlay("glance", at=s.t, dur=0.8, a=pc, b=ch, dy1=150, dy2=150)
    s.wait(0.7)
    pc.to(s.t, 0.2, look=0.6)
    ch.to(s.t, 0.2, look=0.8)
    s.say(ch, "Bro. Please roast us.", eyes="happy", mouth="grin")
    s.say(pc, "It makes the show more fun for everybody.", eyes="happy", mouth="grin")
    s.say(c, "Deal.", mouth="grin", eyes="open", arms="point")
    s.sfx("pop", gain=0.7)
    s.overlay("sfx", dur=0.7, text="BUMP!", x=760, y=930, size=90, color="#ffffff")
    s.wait(0.8)
    s.end()

    # ------------------------------------------------------------------ the roast
    s = P.shot("stage", mood="laugh", banner2="ASSEMBLY #8")
    s.music("comedy", gain=0.3, fade=0.3)
    pc, ch = stage_duo(s, pc_x=230, chad_x=850, pc=dict(eyes="happy", mouth="grin", arms="hips", shades=1),
                       chad=dict(eyes="happy", mouth="grin", arms="hips"))
    c = s.actor("cartman", x=540, y=STAGE_Y, scale=1.0, eyes="half", mouth="smirk", arms="mic", hold="mic", z=1,
                gest=1.0)
    s.camera(cx=540, cy=860, zoom=1.15)
    s.say(c, "PC Principal wears sunglasses indoors because underneath, he has the most caring eyes you've "
             "ever seen. It's disgusting.", look=-0.6)
    pc.to(s.t, 0.4, shades=0.0, eyes="warm", sparkle=1, arms="shades", holdshades=1)
    s.sfx("sparkle", gain=0.6)
    s.sfx("crowd_laugh", gain=0.8, d=2.8)
    s.param(mood="roar")
    s.wait(1.2)
    pc.set(s.t, sparkle=0)
    s.say(c, "And Chad cried at a protein bar commercial. Twice. It was the same commercial.", look=0.6)
    s.sfx("crowd_laugh", gain=0.85, d=2.8)
    s.say(ch, "It was beautiful.", eyes="teary", tears=0.6, mouth="smile", arms="heart", pre=0.4, gap=0.6)
    s.end()

    # ------------------------------------------------------------------ the heckler
    s = P.shot("stands", mood="laugh", target_x=360)
    h = s.actor("heckler", x=360, y=ROW1, scale=0.74, layer=1, seated=1, eyes="half", mouth="smirk")
    s.camera(cx=380, cy=1180, zoom=1.6)
    h.to(0.2, 0.3, "back", y=ROW1 - 60, arms="cup")
    s.wait(0.5)
    s.say(h, "Yeah! They're total freaks!", style="shout", mouth="grin")
    s.say(h, "LOSERS!", style="shout", mouth="scream", eyes="angry")
    s.param(mood="uneasy")
    s.sfx("crowd_laugh", gain=0.3, d=1.4)
    s.cc("[A few kids snicker. It feels off.]", dur=1.9)
    s.wait(0.9)
    s.end()

    s = P.shot("stage", mood="uneasy", banner2="ASSEMBLY #8")
    pc, ch = stage_duo(s, pc_x=230, chad_x=850, pc=dict(eyes="warm", mouth="flat", arms="down", shades=0,
                                                        holdshades=1, brow=0.5, look=0.9),
                       chad=dict(eyes="warm", mouth="flat", arms="down", brow=0.6, look=-0.9))
    c = s.actor("cartman", x=540, y=STAGE_Y, scale=1.0, eyes="open", mouth="flat", arms="down", hold="mic", z=1)
    s.camera(cx=540, cy=760, zoom=1.2)
    s.cc("[The bros don't defend themselves. They look at Cartman.]", dur=2.6, at=0.2)
    s.camera(at=0.9, dur=1.8, ease="inout", cx=540, cy=990, zoom=2.2)
    s.wait(2.3)
    s.think(c, "Losers. Huh. That sounded a lot worse from out here.", icon="...", eyes="half", brow=0.5)
    s.think(c, "That's not roasting. That's just mean.", icon="hmm", eyes="angry", brow=-0.4)
    s.end()

    # ------------------------------------------------------------------ after the show
    s = P.shot("hallway", board=1)
    s.music("tension", gain=0.2, fade=0.5)
    s.overlay("label", at=0.1, dur=1.6, text=["AFTER THE SHOW"], x=540, y=580, size=50)
    h = s.actor("heckler", x=300, y=1560, scale=1.1, eyes="happy", mouth="grin", arms="hips")
    hp = s.actor("hecklerpal", x=60, y=1560, scale=1.05, eyes="happy", mouth="grin")
    c = s.actor("cartman", x=1300, y=1580, scale=1.15, eyes="half", mouth="flat", arms="down", walk=1, z=1)
    s.camera(cx=540, cy=1100, zoom=1.2)
    s.say(h, "Did you see their faces? Total freaks.", pre=0.3)
    s.sfx("crowd_laugh", gain=0.25, d=1.2)
    c.to(0, 2.6, "lin", x=720)
    c.set(2.6, walk=0)
    s.wait(max(0.0, 2.7 - s.t))
    h.to(s.t, 0.3, eyes="open", mouth="flat", look=1)
    s.say(c, "Hey. Those two? They're my co-hosts.", arms="point")
    s.say(c, "I get to roast them, because they're in on it. That's called comedy.", arms="hips")
    s.say(c, "What you did is called being a jerk.", eyes="angry", brow=-0.6)
    s.say(h, "Dude, you call them dweebs all the time.", mouth="smirk", eyes="half")
    s.say(c, "Yeah. MY dweebs. Back off.", eyes="angry", brow=-0.8, mouth="flat")
    c.to(s.t, 0.4, x=560, lean=0.12)
    s.camera(dur=0.5, cx=460, cy=1000, zoom=1.6)
    s.say(c, "Trust me. I've been where you are. Mess around, and you'll find out.", style="whisper", pre=0.3,
          eyes="half")
    h.to(s.t, 0.3, eyes="wide", mouth="o", sweat=1.5, brow=1)
    s.sfx("gulp", gain=0.9)
    s.wait(0.6)
    h.set(s.t, walk=1, facing=-1)
    hp.set(s.t, walk=1, facing=-1)
    h.to(s.t, 1.4, "in", x=-300)
    hp.to(s.t, 1.4, "in", x=-500)
    s.wait(1.2)
    s.end()

    # ------------------------------------------------------------------ the knowing look
    s = P.shot("hallway", board=0)
    s.music("warm", gain=0.45, fade=0.6)
    pc = s.actor("pc", x=380, y=1540, scale=1.15, eyes="warm", mouth="smile", shades=0, arms="cross", look=0.9)
    ch = s.actor("chad", x=720, y=1540, scale=1.15, eyes="teary", mouth="smile", arms="heart", look=-0.9,
                 tears=0.4)
    s.camera(cx=550, cy=950, zoom=1.25)
    s.camera(dur=10, ease="lin", zoom=1.4)
    s.cc("[Down the hall, the bros saw everything]", dur=2.0, at=0.2)
    s.overlay("glance", at=0.6, dur=9.0, a=pc, b=ch, dy1=150, dy2=150)
    s.overlay("hearts", at=0.8, dur=9.0, x0=150, x1=930, y=1500, n=14)
    s.wait(1.0)
    s.say(ch, "Good job, bro.", style="whisper", gap=0.1)
    s.say(pc, "Good job, bro.", style="whisper", gap=0.5)
    s.narr("And somewhere along the way, Eric Cartman stopped being bored.")
    s.wait(0.3)
    s.end()

    s = P.shot("card", card="end", tag="FEELINGS ARE REPS.")
    s.sfx("sting", gain=0.8)
    s.wait(3.0)
    s.end()
    return P.finalize()
