"""
"Yeah. I Know." -- screenplay as data.

Every entry is one of:
  ("line",  id, speaker, text, extra)   spoken line; extra may set speed/gap
  ("pause", seconds)                     silent acting beat
  ("mark",  name)                        named point in time (scene / music cues)
  ("vocal", id, speaker, text, offset, gain)  laugh etc. placed after the previous
                                         line; overlaps the next pause, no caption

The voice pipeline turns this into audio + a timeline; the animation
direction (direction.js) refers to line ids and marks.
"""

VOICES = {
    # speaker: (kokoro voice, base speed, pitch factor applied after synthesis)
    "narrator": ("af_heart", 0.76, 1.00),
    "marcus":   ("am_michael", 0.83, 0.94),   # resampled a touch lower/slower
    "theo":     ("am_fenrir", 0.78, 1.00),
    "priya":    ("af_bella", 0.82, 1.00),
}

SCRIPT = [
    # ---------------------------------------------------------- SCENE 1
    ("mark", "s1"),
    ("pause", 3.1),
    ("line", "T1", "theo", "No, no, no, no... oh, come on!", {"speed": 1.05}),
    ("pause", 0.35),
    ("line", "P1", "priya", "Oh, man! That was so close.", {}),
    ("pause", 0.5),
    ("line", "M1", "marcus", "Theo. Buddy.", {}),
    ("pause", 0.45),
    ("line", "M1b", "marcus", "You are such a screwup.", {"speed": 1.0}),
    ("vocal", "LM1", "marcus", "Ha ha ha!", 0.05, 0.75),
    ("pause", 1.25),
    ("line", "T2", "theo", "Yeah. I know.", {"speed": 0.78}),
    ("mark", "silence"),
    ("pause", 3.4),
    ("line", "N1", "narrator", "Here's the thing about a joke.", {}),
    ("pause", 0.6),
    ("line", "N2", "narrator", "It only works... when everyone in the room knows it isn't true.", {}),
    ("pause", 0.9),
    ("line", "N3", "narrator", "Theo didn't say it like a joke.", {}),
    ("pause", 1.1),
    ("line", "N4", "narrator", "And with three people in the room, that kind of silence doesn't just get heavy. It multiplies.", {}),
    ("pause", 0.9),
    ("line", "P2", "priya", "I think I'll... head home.", {}),
    ("pause", 0.5),
    ("line", "P3", "priya", "Text me, okay?", {"speed": 0.9}),
    ("mark", "priya_exit"),
    ("pause", 2.6),
    ("mark", "door"),
    ("pause", 1.0),
    ("mark", "tv_off"),
    ("pause", 1.6),

    # ---------------------------------------------------------- SCENE 2
    ("mark", "s2"),
    ("line", "M2", "marcus", "Come on, man. I was kidding.", {}),
    ("pause", 0.35),
    ("line", "M2b", "marcus", "You know I was kidding.", {}),
    ("pause", 1.0),
    ("line", "T3", "theo", "I know you were.", {}),
    ("pause", 1.1),
    ("line", "T4", "theo", "That's kind of the problem.", {}),
    ("pause", 1.0),
    ("line", "M3", "marcus", "What's that supposed to mean?", {}),
    ("pause", 1.1),
    ("line", "T5", "theo", "It's never one big thing. It's, relax, sensitive boy. It's, nice one, genius.", {}),
    ("pause", 0.7),
    ("line", "T6", "theo", "Every one of them is tiny. Like... two percent.", {}),
    ("pause", 0.8),
    ("line", "T7", "theo", "But I've been collecting two percents for about six months.", {}),
    ("pause", 1.1),
    ("line", "M4", "marcus", "So what? Now I have to walk on eggshells in my own apartment?", {"speed": 1.06}),
    ("pause", 1.1),
    ("line", "T8", "theo", "No. I'm not asking you to be careful.", {}),
    ("pause", 0.8),
    ("line", "T9", "theo", "I'm asking you to be curious.", {}),
    ("pause", 1.5),
    ("line", "T10", "theo", "Can I ask you something? And tell me if I'm wrong.", {}),
    ("pause", 0.6),
    ("line", "T11", "theo", "When you roast me... what are you actually trying to say?", {}),
    ("mark", "music_soft"),
    ("pause", 2.2),
    ("line", "N5", "narrator", "Anger is often a guard... standing in front of a door.", {}),
    ("pause", 0.6),
    ("line", "N6", "narrator", "And behind that door, there's usually something softer.", {}),
    ("pause", 1.3),
    ("line", "M5", "marcus", "In my unit... nobody said nice stuff. Ever.", {}),
    ("pause", 0.9),
    ("line", "M6", "marcus", "You said, you're an idiot, get in the truck. And that meant... I've got you.", {}),
    ("pause", 1.3),
    ("line", "M7", "marcus", "There was this guy. Danny. We gave him hell. All of us.", {}),
    ("pause", 0.7),
    ("line", "M8", "marcus", "And one day, he just... started agreeing with it.", {}),
    ("pause", 0.9),
    ("line", "M9", "marcus", "Yeah, I'm useless. Yeah, I know.", {"speed": 0.86}),
    ("pause", 0.9),
    ("line", "M10", "marcus", "And we laughed. Took us way too long to figure out he meant it.", {}),
    ("pause", 1.3),
    ("line", "T12", "theo", "Is he okay?", {"speed": 0.82}),
    ("pause", 1.1),
    ("line", "M11", "marcus", "He is now.", {}),
    ("pause", 0.8),
    ("line", "M12", "marcus", "No thanks to me.", {"speed": 0.88}),
    ("pause", 1.7),
    ("line", "T13", "theo", "So when I said it tonight...", {}),
    ("pause", 0.8),
    ("line", "M13", "marcus", "Yeah, it scared the crap out of me.", {}),
    ("mark", "music_warm"),
    ("pause", 1.7),
    ("line", "T14", "theo", "So... you're a screwup, actually means... you're my guy?", {}),
    ("pause", 0.9),
    ("line", "M14", "marcus", "Basically.", {}),
    ("pause", 0.9),
    ("line", "T15", "theo", "Man. That is the most confusing love language I've ever heard.", {}),
    ("vocal", "LM2", "marcus", "Heh heh.", 0.25, 0.7),
    ("vocal", "LT2", "theo", "Heh.", 0.45, 0.6),
    ("pause", 1.6),
    ("line", "T16", "theo", "I get it now. I do. But I wasn't in your unit. I don't have the translation guide.", {}),
    ("pause", 0.6),
    ("line", "T17", "theo", "When it's just the joke, without the, I've got you, part... the joke is all I hear.", {}),
    ("pause", 1.2),
    ("line", "M15", "marcus", "So what am I supposed to do? Look you in the eye and go,", {}),
    ("pause", 0.5),
    ("line", "M15b", "marcus", "Theo, I value you... as a person?", {"speed": 0.84}),
    ("pause", 1.4),
    ("line", "T18", "theo", "Please never do that again.", {}),
    ("vocal", "LM3", "marcus", "Ha ha ha ha!", 0.2, 0.75),
    ("vocal", "LT3", "theo", "Ha ha.", 0.35, 0.65),
    ("pause", 1.6),
    ("line", "T19", "theo", "Keep the roasting. Some of it's funny. Just... every once in a while, say the other part out loud.", {}),
    ("pause", 0.6),
    ("line", "T20", "theo", "And if one lands wrong, I'll tell you. Right then. Not six months later. That part's on me.", {}),
    ("pause", 1.0),
    ("line", "M16", "marcus", "Deal.", {}),
    ("mark", "fistbump"),
    ("pause", 2.0),
    ("line", "M17", "marcus", "And for the record... you're not a screwup.", {"speed": 0.9}),
    ("pause", 1.4),
    ("line", "T21", "theo", "I know.", {"speed": 0.85}),
    ("pause", 1.6),
    ("line", "N7", "narrator", "Same two words. A completely different meaning.", {}),
    ("pause", 1.8),

    # ---------------------------------------------------------- SCENE 3
    ("mark", "s3"),
    ("pause", 3.6),
    ("line", "M18", "marcus", "Theo.", {}),
    ("pause", 0.7),
    ("line", "M19", "marcus", "That is the worst toast I have ever seen in my life.", {}),
    ("pause", 1.3),
    ("line", "M20", "marcus", "I'd still go to war with you, though.", {}),
    ("pause", 0.7),
    ("line", "T22", "theo", "That's weirdly the nicest thing anyone's ever said to me.", {}),
    ("vocal", "LM4", "marcus", "Hah! Ha ha.", 0.15, 0.7),
    ("vocal", "LT4", "theo", "Heh heh heh.", 0.3, 0.55),
    ("mark", "laugh2"),
    ("pause", 1.8),
    ("line", "N8", "narrator", "Most of us were never taught to say the soft thing out loud. So we hide it inside jokes.", {}),
    ("pause", 0.6),
    ("line", "N9", "narrator", "The goal isn't to stop joking.", {}),
    ("pause", 0.5),
    ("line", "N10", "narrator", "It's to make sure the people we love... can still find the love inside it.", {}),
    ("pause", 0.8),
    ("line", "N11", "narrator", "And when they can't... to be brave enough to say so.", {}),
    ("mark", "end"),
    ("pause", 3.2),
]

# Subtitle text when it should differ from what the TTS reads
# (the TTS text uses commas in place of quote marks for better prosody).
CAPTIONS = {
    "T5":  "It's never one big thing. It's “relax, sensitive boy.” It's “nice one, genius.”",
    "M6":  "You said, “you're an idiot, get in the truck.” And that meant... I've got you.",
    "M9":  "“Yeah, I'm useless.” “Yeah, I know.”",
    "T14": "So... “you're a screwup” actually means... “you're my guy”?",
    "T17": "When it's just the joke, without the “I've got you” part... the joke is all I hear.",
    "M15b": "“Theo, I value you... as a person”?",
}
