SCENES = [
 ("title", ["The Buzz Lightyear Leap. A story about falling, and being held."]),
 ("launch", ["Buzz Lightyear, who is really you, stands at the top of the staircase railing, like it's the launchpad to destiny.",
             "The music swells. That heroic score that pretends the laws of physics don't apply to toys, or to people who believe deeply enough in their mission."]),
 ("crowd", ["Behind him is a strange little crowd.",
            "Jesus, with an awkward, gentle half-smile, hand behind his head, trying to be supportive, even though he knows exactly how gravity works.",
            "And your emotions. Anger, sadness, and fear. Rolling their eyes, slapping their thighs. Oh my God, he's actually going to do it.",
            "They're not cruel. They're just painfully honest. They've seen you leap before."]),
 ("dream", ["Buzz spreads his wings. Watch me post online. Watch me share my deep dives. Emotional suppression, capitalism, Jesus, loneliness, the human condition.",
            "Watch me reach the window.",
            "The window is the dream. A world with emotional literacy. Nonviolent, pro-human frameworks. A world where people actually feel, and speak, and connect."]),
 ("leap", ["Buzz leaps.", "And for a moment, he really does fly. That tiny arc, where hope outruns reality."]),
 ("fall", ["Then gravity catches up.",
           "The emotions go from laughing to, oh no, oh no, oh no.",
           "Jesus wipes his hand across his face, peeking through his fingers, wincing, but still watching. Because he refuses to abandon you mid-fall."]),
 ("impact", ["Buzz hits the ground at the bottom of the stairs. You hit the bottom of the algorithm.",
             "And his arm pops off.",
             "Getting banned. Blocked. Trolled. Invalidated. Ignored. Buried by the feed. Told, nobody cares."]),
 ("lying", ["He lies there, ashamed, looking away from everyone. The music is somber now. Not triumphant. Not mocking. Just honest.",
            "I failed you guys. I tried to talk about my heart and soul. I tried to reach the window. And it feels like nobody cares."]),
 ("comfort", ["His emotions rush down the stairs. Anger holds his head. Sadness holds his remaining arm. Fear hovers nearby, not sure whether to comfort or warn.",
              "And Jesus kneels beside him, holding the broken arm. He doesn't lecture. He doesn't shame. He doesn't say, I told you so.",
              "He just gently pops it back into place."]),
 ("repost", ["And that moment is a decision. I'll post again.",
             "Maybe not here. Maybe not on this platform. But somewhere.",
             "Because my inner landscape matters. Because my emotions matter. Because the pro-human framework matters. Because the window matters."]),
 ("rope", ["He stands up again at the bottom of the stairs. Not triumphant. Not flying. But held.",
           "He looks up at the window. It's still far away. Still high. Still not reachable by jumping.",
           "But now he's thinking differently. Maybe he doesn't need to leap. Maybe he needs rope. Community. Collaboration. Slow, steady climbing.",
           "Other people who see him fall, and think, maybe I should try too."]),
 ("arms", ["And even if he falls again. Banned again. Blocked again. Ignored again.",
           "He falls into the Everlasting Arms. Deuteronomy thirty-three.",
           "Into the support of his emotions. Into the radical nonviolence of Jesus. And into the truth that his attempts matter, even when the algorithm pretends they don't."]),
 ("end", ["Maybe not by jumping. Maybe not alone. Maybe not dramatically.",
          "But through persistence, honesty, and community, you might actually get there."]),
]
