# id: (speaker, spoken_text, caption_text, speed)
VOICES = {
    "NARR": ("bm_george", "en-gb"),
    "LORD": ("am_puck", "en-us"),
    "WHISP": ("am_puck", "en-us"),
    "CREATOR": ("am_michael", "en-us"),
    "THER": ("af_heart", "en-us"),
    "SJW": ("af_bella", "en-us"),
    "GREG": ("am_fenrir", "en-us"),
    "LINDA": ("af_sarah", "en-us"),
}
LINES = {
 "A1": ("NARR", "Somewhere on the internet, a humble dweeb is cooking up some meme science.", None, 0.95),
 "A2": ("CREATOR", "Okay, Consciousness AI. Let's cook!", "Okay, Consciousness AI™... let's cook!", 1.0),
 "A3": ("NARR", "The Chuckle That Broke the Unbreakable.", None, 0.9),
 "B1": ("NARR", "Meanwhile, in a dimly lit bedroom, we observe the Logical Lord, in his natural habitat.", None, 0.95),
 "B2": ("NARR", "Cheeto-dusted keyboard. Three energy drinks deep.", None, 0.95),
 "B3": ("NARR", "Webcam light? Irrelevant.", None, 0.95),
 "B4": ("LORD", "Well, actually, humor is subjective.", None, 0.95),
 "B5": ("LORD", "Oh ho! What's this?", "Oh-ho. What's this?", 1.0),
 "B6": ("LORD", "Ha. Look at this dweeb, using his pretty little AI tool,", "Ha. Look at this dweeb, using his pretty little AI tool...", 1.0),
 "B7": ("LORD", "to make some... luh humorous post.", "...to make some “le humorous post.”", 0.95),
 "B8": ("NARR", "He cracks his knuckles. Ready to roast.", None, 0.95),
 "C1": ("NARR", "He clicks. He reads.", None, 0.95),
 "C2": ("NARR", "For legal reasons, we cannot show you the post.", None, 0.95),
 "C3": ("NARR", "But then... Bam!", "But then... BAM.", 0.95),
 "C4": ("NARR", "He senses it. The forbidden chuckle.", None, 0.92),
 "C5": ("NARR", "Bubbling up from deep in the gut, like some ancient, primordial force.", None, 0.95),
 "C6": ("WHISP", "No. No, no, no! I can't laugh at this dweeb's post!", None, 1.0),
 "C7": ("WHISP", "I'm the Logical Lord of Reddit. If I laugh... I lose.", None, 1.05),
 "D1": ("NARR", "He clamps his mouth shut. Eyes watering. Face going full tomato.", None, 0.97),
 "D2": ("NARR", "And then... his body betrays him.", None, 0.92),
 "D3": ("NARR", "A long, glorious honk of surrender.", None, 0.92),
 "D4": ("LORD", "That... didn't happen.", None, 0.9),
 "D5": ("NARR", "Oh, it happened.", None, 0.95),
 "E1": ("NARR", "Desperate, he builds a mental fortress of unfunny thoughts.", None, 0.97),
 "E2": ("LORD", "Un-funny thoughts. Think un-funny thoughts.", "Unfunny thoughts. Think unfunny thoughts.", 1.0),
 "E3": ("NARR", "A therapist. Nodding blankly.", None, 0.95),
 "E4": ("THER", "Mm-hm. And how does that make you feel?", "Mm-hmm. And how does that make you feel?", 0.88),
 "E5": ("NARR", "A social justice warrior, with a pie chart.", None, 0.97),
 "E6": ("SJW", "Um, I made a pie chart of everything that's problematic. And honestly? The pie chart is problematic.", None, 1.1),
 "E7": ("NARR", "A happy nuclear family in the suburbs. Mowing the lawn. Sipping lukewarm lattes.", None, 0.97),
 "E8": ("GREG", "Honey, I edged the lawn.", None, 0.95),
 "E9": ("LINDA", "Oh, Greg. You always edge the lawn.", None, 0.95),
 "E10": ("NARR", "But when even a happy normie couple can't stop the laughter...", None, 0.97),
 "F1": ("NARR", "the Logical Lord collapses in a heap.", "...the Logical Lord collapses in a heap.", 0.92),
 "F2": ("NARR", "This is not a laugh. It's a soul evacuation.", None, 0.92),
 "F3": ("NARR", "A chuckle held in so long, it was poisoned by his lame-ass, anti-fun soul.", None, 0.95),
 "F4": ("NARR", "Like a sad, deflating balloon, making the saddest clown noises,", None, 0.95),
 "F5": ("NARR", "for one. Full. Minute.", None, 0.85),
 "G1": ("NARR", "And the webcam?", None, 0.92),
 "G2": ("NARR", "The webcam... was on.", None, 0.85),
 "G3": ("LORD", "Is that... recording?", None, 0.85),
 "H1": ("NARR", "Deep in the bowels of the internet, the clip goes viral.", None, 0.97),
 "H2": ("NARR", "Somebody autotunes it.", None, 0.95),
 "R1": ("LORD", "I'm the Logical Lord.", None, 0.9),
 "R2": ("LORD", "If I laugh, I lose.", None, 0.9),
 "I1": ("NARR", "Moral of the story?", None, 0.95),
 "I2": ("NARR", "Post the damn meme.", None, 0.9),
 "I3": ("NARR", "You're not just making content. You're a catalyst for chaos and comedy,", None, 0.95),
 "I4": ("NARR", "one suppressed laugh at a time.", None, 0.92),
 "I5": ("NARR", "Keep going, you unhinged genius.", None, 0.95),
}
