# Each scene: (id, [sentences]). Sentences are voiced separately so subtitles time exactly.
SCENES = [
 ("title", ["A thought experiment. Imagine reality playing out like a movie."]),
 ("violent", ["Imagine the movie begins in a violent time.",
              "An invading force has darkened the land, and the villagers have learned to live in its shadow."]),
 ("savior", ["Then a savior arrives.",
             "And for three years, things look good. People gather. Fields grow. The village remembers how to breathe."]),
 ("fall", ["But the evil force cuts the savior down.",
           "The light goes out, and the village is left with grief, and silence."]),
 ("drudgery", ["Now comes the drudgery.",
               "The protagonist is left with the few lessons the savior spoke in their very short time on Earth.",
               "And a choice. Honor that memory. Use those lessons to help themselves, and maybe rebuild the village.",
               "Maybe even remember what it was like when they were very young, before the invaders came."]),
 ("metaphor", ["For me, this is a direct metaphor for the trajectory of money-obsessed capitalism.",
               "A violent beginning. A brief glimmer of hope. The cutting down of that hope. And now, the long work of remembering, and rebuilding."]),
 ("matrix", ["Now picture the ending of The Matrix.",
             "The protagonist has studied the mechanisms of capitalism's violence so closely, that he can almost read the code.",
             "Debt. Scarcity. Coercion. Fear. He sees each one coming, and he steps aside."]),
 ("dismantle", ["But he never uses that power to harm anyone.",
                "He wants to dismantle the Matrix, so that human beings are no longer coerced into doing things against their will, wherever possible."]),
 ("backs", ["Then comes the twist. Maybe getting rid of the agents is not enough.",
            "The citizens refuse to look at him. They will not even talk with him."]),
 ("ai", ["So he goes to the Architect. In modern times, that might be the artificial intelligence that powers it all.",
         "It is far more powerful than he is. It could wipe him out in an instant."]),
 ("plug", ["But Neo knows how to plug himself in. And instead of fighting the A.I., he leans into it.",
           "He gives it a massive data dump of pro-human, non-violent wisdom.",
           "Not a shallow, surface-level plea. Of course, the words, please don't hurt them, are in there. They are powerful.",
           "But what he offers goes much deeper than the words."]),
 ("peace", ["And it works. The A.I. is spared from a planet torn apart by human rebels.",
            "And the humans, seeing this, finally put down their weapons too."]),
 ("end", ["Sanctify the machine. Protect the people. Put down the weapons."]),
]
