"""DO NOT DISTURB, PART 3: THE HARVEST"""
from .common import new_part, title, hop_loop


def build():
    P = new_part(3, "THE HARVEST", "dnd3-the-harvest")
    title(P, 3, "THE HARVEST")

    # ------------------------------------------------------------------ the lobby
    s = P.shot("d_lobby", gate=0)
    s.music("muzak", gain=0.35, fade=0.4)
    rc = s.actor("recept", x=250, y=1400, scale=0.95, mouth="smile", eyes="open", look=0.8)
    gd = s.actor("guard", x=1000, y=1520, scale=0.95, eyes="half", mouth="flat", arms="cross", layer=1, look=-0.8)
    td = s.actor("tired", x=1300, y=1560, scale=1.05, arms="hold", hold="clipboard", eyes="half", mouth="flat",
                 bandage=1, walk=0.7, layer=1)
    td.to(0, 2.0, "lin", x=600)
    td.set(2.0, walk=0)
    s.camera(cx=560, cy=1100, zoom=1.15)
    s.wait(2.0)
    s.say(rc, "Welcome to Calm Corp. Do you have an appointment?")
    s.say(td, "I'm here about the thing.", look=-0.8)
    s.say(rc, "What thing?", eyes="wide", brow=0.6)
    s.say(td, "Exactly.", gap=0.5)
    rc.to(s.t - 0.4, 0.1, blink=1)
    rc.to(s.t - 0.2, 0.1, blink=0)
    s.say(gd, "Badge?")
    s.say(td, "Fourth floor. Something's making a noise. They called me. I don't want to be here either.",
          look=0.8)
    s.wait(0.4)
    s.camera(dur=0.5, cx=900, cy=900, zoom=1.9)
    s.wait(0.8)
    s.say(gd, "Yeah. You look like you don't want to be here.", eyes="half")
    s.sfx("buzz", gain=0.8)
    s.param(dur=0.4, gate=1)
    s.camera(dur=0.5, cx=640, cy=1100, zoom=1.15)
    s.overlay("label", at=s.t + 0.3, dur=2.0, text=["SECURITY LEVEL:", "TOO BORED TO ASK"], x=540, y=560,
              size=46, bg="#9ed8c4")
    td.set(s.t + 0.4, walk=0.7)
    td.to(s.t + 0.4, 1.6, "lin", x=1300)
    s.wait(2.2)
    s.end()

    # ------------------------------------------------------------------ the hallway
    s = P.shot("d_hall")
    sc = s.actor("sci", x=900, y=1500, scale=1.0, arms="hold", hold="clipboard", eyes="open", mouth="flat",
                 walk=0.6)
    td = s.actor("tired", x=100, y=1520, scale=1.05, arms="hold", hold="clipboard", eyes="half", mouth="flat",
                 bandage=1, walk=0.7)
    td.to(0, 6.0, "lin", x=900)
    sc.to(0, 6.0, "lin", x=200)
    s.camera(cx=500, cy=1100, zoom=1.2)
    s.say(sc, "Excuse me. Who are you?", pre=0.4, look=0.6)
    s.say(td, "Facilities. Checking the vibes.", look=0.6)
    s.say(sc, "The what?", eyes="wide")
    s.say(td, "They're fine. Keep it up.")
    s.say(sc, "Thanks?", mouth="smile", gap=0.4)
    s.end()

    # ------------------------------------------------------------------ the lab
    s = P.shot("d_lab", tank_label="SUBJECT 7: ESCAPED", sketch=1, screen=[
        "SUBJECT 7", "STATUS: ESCAPED", "LOCATION: UNKNOWN", "", "FRAGMENTS SHED BY", "SUBJECT 7 ARE MOBILE.",
        "FRAGMENT BITES MAY", "TRANSFER: STRENGTH,", "ENDURANCE, SENSES."])
    s.music("spy", gain=0.35, fade=0.3)
    td = s.actor("tired", x=420, y=1500, scale=1.05, arms="down", eyes="half", mouth="flat", bandage=1)
    s.camera(cx=540, cy=1000, zoom=1.05)
    s.wait(0.8)
    s.camera(dur=1.0, cx=790, cy=600, zoom=1.9)
    s.cc("[Subject 7. Escaped.]", at=0.8, dur=2.4)
    s.wait(3.0)
    s.camera(dur=0.6, cx=500, cy=1000, zoom=1.4)
    td.to(s.t, 0.4, looky=0.9, look=0.6, arms="hold2")
    s.say(td, "Oh. That's not great.", pre=0.4)
    td.to(s.t, 0.3, looky=0, look=0.5, eyes="squint")
    s.say(td, "So the thing in the cage was only a piece of it.")
    s.say(td, "The real one is still out there.", eyes="open")
    # leans on the console...
    td.set(s.t, walk=0.5)
    td.to(s.t, 0.8, x=760, lean=0.15, arms="lean")
    td.set(s.t + 0.8, walk=0)
    s.wait(0.9)
    s.param(dur=0.1, pressed=1)
    s.sfx("click", gain=1.0)
    s.wait(0.3)
    s.music(None, fade=0.05)
    s.param(alarm=1)
    s.sfx("alarm", gain=0.7)
    s.overlay("sfx", dur=1.0, text="ALERT! ALERT!", x=540, y=500, size=110, color="#ff3b3b")
    s.wait(0.6)
    s.say(td, "Of course.", eyes="half", lean=0, gap=0.3)
    s.end()

    # ------------------------------------------------------------------ the chase
    s = P.shot("d_hall", alarm=1, window_x=2600, cam_x=300)
    s.music("chase", gain=0.5, fade=0.05)
    s.sfx("alarm", gain=0.45)
    s.sfx("alarm", at=4.0, gain=0.45)
    td = s.actor("tired", x=300, y=1520, scale=1.0, arms="out", eyes="wide", mouth="o", bandage=1, walk=1.5)
    g1 = s.actor("guard", x=-350, y=1520, scale=1.0, arms="reach", eyes="angry", mouth="o", walk=1.5)
    g2 = s.actor("guard2", x=-600, y=1520, scale=1.0, arms="reach", eyes="angry", mouth="o", walk=1.5)
    T = 4.6
    td.to(0, T, "lin", x=2520)
    g1.to(0, T, "lin", x=1900)
    g2.to(0, T, "lin", x=1650)
    s.camera(cx=300, cy=1100, zoom=1.0)
    s.camera(dur=T, ease="lin", cx=2250)
    s.param(dur=T, ease="lin", cam_x=2250)
    s.say(g1, "STOP RIGHT THERE!", style="shout", pre=0.3, advance=False)
    s.wait(1.9)
    s.say(td, "Why is there always running?", style="mutter", advance=False)
    s.wait(T - 1.9)
    td.set(s.t, walk=0, arms="down")
    g1.set(s.t, walk=0)
    g2.set(s.t, walk=0)
    s.wait(0.2)
    td.to(s.t, 0.3, look=1, eyes="half")
    s.wait(0.4)
    td.to(s.t, 0.3, look=-1)
    s.wait(0.4)
    s.say(td, "Nope.", eyes="half", look=0)
    # through the window
    td.set(s.t, arms="up", walk=1.5)
    td.to(s.t, 0.4, "in", x=2800, rot=0.6, y=1300)
    s.sfx("glass", at=s.t + 0.3, gain=1.0)
    s.param(at=s.t + 0.3, smashed=1, smash_t=s.t + 0.3)
    s.overlay("flash", at=s.t + 0.3, dur=0.3, alpha=0.6)
    s.overlay("sfx", at=s.t + 0.3, dur=0.8, text="SMASH!", x=540, y=600, size=140, color="#9ed8c4")
    td.set(s.t + 0.45, visible=0)
    s.wait(1.1)
    s.end()

    # ------------------------------------------------------------------ the fall
    s = P.shot("d_fall", shatter=1, shatter_t=0.0, shatter_x=540, shatter_y=-5560)
    s.music(None, fade=0.1)
    s.sfx("wind", gain=0.9)
    s.sfx("wind", at=2.9, gain=1.0)
    td = s.actor("tired", x=520, y=-5300, scale=0.9, rot=0.4, arms="up", flail=1.0, eyes="wide", mouth="scream",
                 bandage=1)
    FALL = 6.0
    td.to(0, FALL, "in", y=1560)
    td.to(0, FALL, "lin", rot=6.0)
    s.camera(cx=540, cy=-5400, zoom=1.0)
    s.camera(dur=FALL, ease="in", cy=1100)
    s.think(td, "So this is how it ends. Tired, and falling.", icon="RIP", pre=0.2)
    s.overlay("label", at=s.t, dur=2.4, text=["LIFE FLASHING", "BEFORE HIS EYES:", "NAP. GAME. NAP.", "GAME. NAP."],
              x=540, y=520, size=46, bg="#efe6d2")
    s.wait(0.8)
    s.think(td, "Honestly? Fair.", icon="...")
    s.wait(max(0.0, FALL - 1.2 - s.t))
    # the powers kick in, a split second too late to see
    td.set(s.t, glow=1.0)
    s.sfx("sense", gain=0.9)
    s.overlay("flash", dur=0.4, alpha=0.35, color="#7ff0dc")
    s.wait(max(0.0, FALL - s.t))
    s.sfx("impact", gain=1.0)
    s.camera(shake=20)
    s.wait(0.15)
    s.end()

    s = P.shot("d_black")
    s.wait(2.2)
    s.end()

    # ------------------------------------------------------------------ the sewers
    s = P.shot("d_sewer", eyes=0, light_x=420, light_y=1350)
    s.music("eerie", gain=0.45, fade=2.0)
    s.sfx("drip", at=0.4, gain=0.8)
    s.sfx("drip", at=1.9, gain=0.6)
    td = s.actor("tired", x=380, y=1420, scale=1.0, rot=-1.45, eyes="closed", mouth="flat", bandage=1, bruise=1,
                 arms="out")
    s.overlay("fade", at=0, dur=1.6, dir="in")
    s.camera(cx=420, cy=1250, zoom=1.6)
    s.wait(1.8)
    td.to(s.t, 0.2, eyes="half")
    td.to(s.t + 0.3, 0.2, eyes="closed")
    td.to(s.t + 0.7, 0.2, eyes="half")
    s.wait(1.0)
    s.say(td, "Ow.", mouth="frown")
    td.to(s.t, 0.8, rot=0.0, y=1500, arms="down")
    s.wait(0.9)
    s.say(td, "Where am I?", eyes="open", brow=0.6)
    s.say(td, "Why does everything smell like everything?", mouth="frown", eyes="squint")
    s.end()

    s = P.shot("d_sewer", eyes=1, light_x=540, light_y=1250)
    td = s.actor("tired", x=150, y=1500, scale=1.0, eyes="half", mouth="frown", bandage=1, bruise=1, walk=0.5,
                 arms="out", shiver=0.15)
    td.to(0, 4.0, "lin", x=560)
    td.set(4.0, walk=0)
    s.camera(cx=540, cy=1150, zoom=1.15)
    s.sfx("drip", at=0.5, gain=0.6)
    s.sfx("drip", at=2.6, gain=0.6)
    s.wait(1.2)
    s.think(td, "Something is watching me.", icon="!?")
    s.wait(1.0)
    s.end()

    # ------------------------------------------------------------------ a new sense, and the real creature
    s = P.shot("d_sewer", eyes=0, sense=0, light_x=540, light_y=1250, sense_x=540, sense_y=1250)
    s.music(None, fade=0.6)
    td = s.actor("tired", x=540, y=1500, scale=1.0, eyes="half", mouth="flat", bandage=1, bruise=1)
    cr = s.actor("creature", x=1300, y=1200, scale=0.62, form=0.0, writhe=1.0, visible=0, z=1)
    s.camera(cx=540, cy=1150, zoom=1.3)
    s.wait(0.6)
    td.to(s.t, 0.4, eyes="wide", glow=0.8)
    s.param(dur=0.5, sense=1.0)
    s.sfx("sense", gain=0.9)
    s.sfx("heartbeat", at=s.t + 0.6, gain=0.8)
    s.sfx("heartbeat", at=s.t + 1.5, gain=0.8)
    s.wait(0.6)
    s.think(td, "I can feel it. Moving behind the wall.", icon="!!")
    s.think(td, "That is not a normal thing to know.", icon="?!")
    # it leaps
    s.param(dur=0.3, sense=0)
    cr.set(s.t, visible=1)
    cr.to(s.t, 0.45, "out", x=640, y=1330)
    s.sfx("shriek", gain=0.9)
    s.overlay("sfx", dur=0.8, text="SKREEEE!", x=700, y=500, size=120, color="#ff5f87")
    s.wait(0.35)
    td.set(s.t, arms="catch", glow=1.0)
    s.camera(at=s.t, dur=0.2, shake=14, zoom=1.6, cy=1150)
    s.wait(0.2)
    s.end()

    s = P.shot("d_sewer", eyes=0, sense=0, light_x=540, light_y=1250, sense_x=560, sense_y=1200)
    s.music("eerie", gain=0.3, fade=0.3)
    td = s.actor("tired", x=520, y=1500, scale=1.0, eyes="wide", mouth="grimace", arms="catch", bandage=1,
                 bruise=1, glow=1.0, shiver=0.6)
    cr = s.actor("creature", x=570, y=1300, scale=0.55, form=0.0, writhe=1.0, z=1)
    s.camera(cx=540, cy=1150, zoom=1.6)
    s.camera(dur=0.3, shake=10)
    s.sfx("hiss", gain=0.8)
    s.sfx("growl", at=0.4, gain=0.6)
    s.say(td, "Nope. Nope. Nope.", pre=0.3, mouth="grimace")
    s.camera(dur=0.5, shake=0)
    s.cc("[He holds it. It can't get loose.]", dur=2.0)
    s.wait(1.4)
    # it realizes: same strength, same senses
    cr.to(s.t, 0.3, writhe=0.2)
    s.param(dur=0.4, sense=1.0)
    s.sfx("sense", gain=0.8)
    s.wait(0.6)
    cr.to(s.t, 2.0, "inout", form=1.0, writhe=0.0)
    cr.set(s.t + 1.2, eyes="wide")
    td.to(s.t, 2.0, shiver=0, eyes="open", mouth="o")
    s.music("tender", at=s.t + 1.0, gain=0.4, fade=1.5)
    s.wait(2.4)
    s.param(dur=0.6, sense=0)
    cr.set(s.t, eyes="happy", blush=1.0)
    s.sfx("purr", gain=0.9)
    s.overlay("hearts", at=s.t, dur=3.5, x0=400, x1=700, y=1300, n=6)
    s.wait(0.6)
    s.say(td, "Are you cuddling me?", eyes="open", mouth="flat", glow=0.4)
    s.wait(0.4)
    td.to(s.t, 0.3, look=0.6, looky=0.5)
    cr.to(s.t, 0.3, eyes="open", look=-0.4, looky=-0.6)
    s.cc("[Neither of them knows what to do. They feel connected.]", dur=2.6)
    s.wait(2.8)
    s.end()

    # ------------------------------------------------------------------ the follower
    s = P.shot("d_sewer", eyes=0, light_x=540, light_y=1250)
    td = s.actor("tired", x=100, y=1500, scale=1.0, eyes="half", mouth="frown", bandage=1, bruise=1, walk=0.6)
    cr = s.actor("creature", x=-250, y=1430, scale=0.42, form=1.0, eyes="happy", z=1)
    td.to(0, 4.4, "lin", x=760)
    cr.to(0, 4.4, "lin", x=430)
    hop_loop(cr, 0, 9, 0.5, 30)
    s.camera(cx=420, cy=1150, zoom=1.15)
    s.camera(dur=4.4, ease="lin", cx=640)
    s.sfx("chitter", at=1.0, gain=0.5)
    s.say(td, "Why me? Why do I have a creature now?", style="mutter", pre=0.6)
    s.wait(max(0.0, 4.4 - s.t))
    td.set(s.t, walk=0)
    s.end()

    s = P.shot("d_sewer", eyes=0, arches=[(240, 460), (840, 460)], sign=1, sign_x=840, light_x=540,
               light_y=1250)
    td = s.actor("tired", x=560, y=1500, scale=1.0, eyes="half", mouth="frown", bandage=1, bruise=1, look=0.8)
    cr = s.actor("creature", x=360, y=1430, scale=0.42, form=1.0, eyes="open", z=1)
    s.camera(cx=540, cy=1100, zoom=1.0)
    s.say(td, "There's no way out of here.", pre=0.3)
    s.sfx("chitter", gain=0.7)
    cr.to(s.t, 0.4, point=1.0, point_dir=3.1, look=-1)
    s.cc("[It points left. Down. Into the dark.]", dur=1.8)
    s.wait(1.6)
    s.say(td, "No. Up is out. That way goes down.", arms="point", look=0.8)
    cr.to(s.t, 0.3, eyes="roll", point=0)
    s.wait(1.0)
    # poke poke poke
    for k in range(4):
        cr.to(s.t + k * 0.35, 0.15, x=430, point=0.6, point_dir=0.0)
        cr.to(s.t + k * 0.35 + 0.17, 0.15, x=380, point=0.2)
        s.sfx("poke", at=s.t + k * 0.35 + 0.15, gain=0.8)
    cr.set(s.t, eyes="half")
    s.say(td, "Okay. Okay! I get it!", mouth="frown", advance=False)
    s.wait(1.5)
    cr.to(s.t, 0.4, x=780, eyes="half")
    s.wait(0.5)
    s.say(td, "Fine. FINE.", eyes="roll", looky=-1, style="shout")
    td.set(s.t, walk=0.6, eyes="half", looky=0)
    td.to(s.t, 1.4, "in", x=-100)
    cr.to(s.t + 0.3, 1.2, "in", x=-100, eyes="happy")
    s.wait(1.3)
    s.end()

    # ------------------------------------------------------------------ the chamber
    s = P.shot("d_chamber")
    s.music("reveal", gain=0.55, fade=1.5)
    td = s.actor("tired", x=440, y=1500, scale=0.9, eyes="half", mouth="flat", bandage=1, bruise=1, walk=0.6)
    cr = s.actor("creature", x=650, y=1500, scale=0.42, form=1.0, eyes="open", z=1)
    td.to(0, 1.0, "out", x=480)
    td.set(1.0, walk=0)
    s.camera(cx=540, cy=1250, zoom=1.7)
    s.wait(1.0)
    td.to(s.t, 0.3, eyes="wide", mouth="o", looky=-0.6)
    s.sfx("dun", gain=0.7)
    s.camera(dur=4.5, ease="inout", cx=540, cy=300, zoom=0.62)
    s.cc("[A chamber as deep as a skyscraper is tall. Pod after pod after pod.]", at=s.t + 0.6, dur=3.4)
    s.wait(5.0)
    s.camera(dur=2.0, ease="inout", cx=540, cy=900, zoom=0.9)
    s.overlay("label", at=s.t + 1.0, dur=2.6, text=["CALM CORP", "HARVEST ARRAY"], x=540, y=500, size=50,
              bg="#9ed8c4")
    s.wait(2.4)
    s.end()

    s = P.shot("d_chamber")
    td = s.actor("tired", x=480, y=1500, scale=0.9, eyes="wide", mouth="o", bandage=1, bruise=1, looky=-0.4)
    cr = s.actor("creature", x=650, y=1500, scale=0.42, form=1.0, eyes="open", looky=-0.5, z=1)
    s.camera(cx=560, cy=1230, zoom=1.9)
    s.wait(0.6)
    s.sfx("whimper", gain=0.8)
    cr.to(s.t, 0.6, looky=0.3, eyes="half")
    s.cc("[Each pod holds a creature like this one. Asleep.]", at=s.t + 0.2, dur=2.8)
    s.wait(1.6)
    td.to(s.t, 0.8, look=0.8, looky=0.4, eyes="sad", brow=1.0, mouth="frown")
    s.wait(1.4)
    s.say(td, "These are your family. Aren't they?", speed=0.92)
    cr.to(s.t + 0.2, 0.3, looky=0.6)
    cr.to(s.t + 0.5, 0.3, looky=-0.2)
    cr.to(s.t + 0.8, 0.4, x=600)
    s.sfx("whimper", at=s.t + 0.6, gain=0.6)
    s.wait(1.8)
    s.say(td, "Okay. I'm awake now.", eyes="open", brow=0.3, mouth="flat", speed=0.9, gap=1.0)
    s.end()

    s = P.shot("d_card", card="end", big="TO BE", big2="CONTINUED?", tag="DO NOT DISTURB")
    s.sfx("dun", gain=0.8)
    s.wait(3.0)
    s.end()
    return P.finalize()
