"""DO NOT DISTURB, PART 1: THE THING UNDER THE DOOR"""
from .common import new_part, title, tbc, hop_loop, ROOM_FLOOR, CHAIR_Y, KITCHEN_FLOOR
from .places import STAIR_BOTTOM, STAIR_TOP


def build():
    P = new_part(1, "THE THING UNDER THE DOOR", "dnd1-the-thing-under-the-door")
    title(P, 1, "THE THING UNDER THE DOOR")

    # ------------------------------------------------------------------ Tiredness, gaming
    s = P.shot("d_room", chair=1, tv=1)
    s.music("lofi", gain=0.35, fade=0.5)
    td = s.actor("tired", x=540, y=CHAIR_Y, scale=1.1, sit=1, arms="hold2", hold="controller", eyes="half",
                 mouth="flat", phones=0)
    s.camera(cx=540, cy=1080, zoom=1.2)
    s.sfx("game", gain=0.35)
    s.sfx("game", at=2.0, gain=0.3)
    s.wait(1.6)
    # commotion outside
    s.sfx("clatter", gain=0.9)
    s.param(dur=0.7, ease="lin", blur_x=600)
    s.param(at=s.t + 0.75, blur_x=-999)
    s.say("emb", "Where are you?! Come back!", fx="far", advance=False)
    td.to(s.t + 0.3, 0.3, look=-0.7)
    s.wait(1.6)
    # eye roll, sigh, headphones on
    td.to(s.t, 0.3, eyes="roll", looky=-1, look=0)
    s.sfx("sigh", at=s.t + 0.2, gain=0.9)
    s.overlay("sfx", at=s.t + 0.2, dur=1.0, text="*SIGH*", x=760, y=760, size=80, color="#efe6d2", rot=0.05)
    s.wait(1.2)
    td.to(s.t, 0.3, eyes="half", looky=0, arms="phone_ear")
    td.set(s.t + 0.3, phones=1)
    s.sfx("click", at=s.t + 0.3)
    s.music("lofi_muffled", at=s.t + 0.3, gain=0.6, fade=0.05)
    s.cc("[Noise canceling: ON]", at=s.t + 0.4, dur=1.6)
    td.to(s.t + 0.5, 0.3, arms="hold2", music=1)
    s.wait(2.0)
    s.sfx("clatter:muffled", gain=0.6)
    s.wait(1.0)
    # the room shakes
    s.sfx("rumble", gain=1.0)
    s.camera(dur=0.2, shake=18)
    s.camera(at=s.t + 1.6, dur=0.4, shake=0)
    s.param(dust=1)
    s.cc("[The whole room shakes]", dur=1.8)
    td.to(s.t + 0.2, 0.2, eyes="wide", mouth="o", music=0, shiver=0.6)
    s.wait(2.0)
    td.to(s.t, 0.3, phones=0.75, arms="phone_ear", shiver=0)
    s.wait(0.3)
    s.say(td, "What the actual [bleep] is going on?", caption="What the actual f*** is going on?",
          eyes="open", mouth="frown", brow=-0.5)
    s.end()

    # ------------------------------------------------------------------ nothing outside
    s = P.shot("d_room", chair=1, tv=1)
    td = s.actor("tired", x=540, y=ROOM_FLOOR, scale=1.15, eyes="open", mouth="frown", phones=0.75, walk=1,
                 arms="down")
    td.to(0, 1.2, "inout", x=250)
    td.set(1.2, walk=0)
    s.camera(cx=360, cy=900, zoom=1.35)
    s.camera(dur=1.2, cx=250, cy=740, zoom=1.9)
    s.wait(1.3)
    td.to(s.t, 0.3, looky=-0.6, look=-0.5, eyes="squint")
    s.sfx("crickets", gain=0.6, d=2.2)
    s.cc("[Nothing. Nobody. An empty street.]", dur=2.0)
    s.wait(2.2)
    td.to(s.t, 0.3, eyes="half", look=0, looky=0, phones=1)
    s.wait(0.3)
    s.end()

    s = P.shot("d_room", chair=1, tv=1)
    s.music("lofi_muffled", gain=0.6, fade=0.3)
    td = s.actor("tired", x=540, y=CHAIR_Y, scale=1.1, sit=1, arms="hold2", hold="controller", eyes="half",
                 mouth="flat", phones=1)
    s.camera(cx=540, cy=1060, zoom=1.6)
    s.say(td, "Why can't people just leave me alone? I'm trying to play a game here.", style="mutter",
          mouth="frown", pre=0.3)
    s.wait(0.3)
    s.end()

    # ------------------------------------------------------------------ Embarrassment, outside
    s = P.shot("d_house")
    s.music("panic", gain=0.45, fade=0.1)
    em = s.actor("emb", x=-150, y=1500, scale=0.95, arms="hold", hold="cage", cage_open=1, cage_full=0,
                 eyes="wide", mouth="grimace", walk=1, sweat=2)
    s.camera(cx=540, cy=1100, zoom=1.1)
    em.to(0, 1.4, "out", x=820)
    em.set(1.4, walk=0)
    s.wait(0.6)
    s.say(em, "Oh God. Oh God. My boss is going to be so pissed at me. I have to find this thing!",
          mouth="wobbly", gest=1.0)
    s.param(cans_down=1)
    s.sfx("clatter", gain=0.8)
    em.to(s.t, 0.25, x=900, rot=0.5, y=1530)
    em.to(s.t + 0.6, 0.25, x=200, rot=0.0, y=1500, walk=1)
    em.set(s.t + 1.2, walk=0)
    em.to(s.t + 1.25, 0.3, rot=-0.6, y=1540)
    s.sfx("rustle", at=s.t + 1.3, gain=0.6)
    s.wait(1.8)
    em.to(s.t, 0.3, rot=0, y=1500)
    s.wait(0.3)
    s.end()

    # the thing slips under the front door
    s = P.shot("d_house")
    th = s.actor("thing", x=900, y=1440, scale=0.75, k=1.0)
    s.camera(cx=560, cy=1320, zoom=2.4)
    th.to(0, 1.0, "inout", x=550)
    s.sfx("chitter", gain=0.7)
    s.sfx("stairscratch", gain=0.4)
    th.to(1.0, 0.25, sy=0.3, y=1420)
    th.set(1.3, visible=0)
    s.wait(1.6)
    s.end()

    # banging on the door
    s = P.shot("d_house")
    em = s.actor("emb", x=560, y=1460, scale=0.95, arms="up", hold="cage", cage_open=1, cage_full=0,
                 eyes="wide", mouth="scream", sweat=2)
    s.camera(cx=560, cy=1060, zoom=1.5)
    s.sfx("bang", gain=1.0)
    hop_loop(em, 0, 3, 0.33, 14)
    s.overlay("sfx", at=0.0, dur=1.0, text="BANG! BANG!", x=560, y=640, size=110, color="#ff7b54")
    s.say(em, "Hello?! Hello! Anybody home?!", style="shout", pre=0.9)
    s.end()

    s = P.shot("d_room", chair=1, tv=1)
    s.music("lofi_muffled", gain=0.6, fade=0.05)
    td = s.actor("tired", x=540, y=CHAIR_Y, scale=1.1, sit=1, arms="hold2", hold="controller", eyes="closed",
                 mouth="smile", phones=1, music=1)
    hop_loop(td, 0, 4, 0.75, 8)
    s.camera(cx=540, cy=1080, zoom=1.3)
    s.sfx("bang:muffled", gain=0.5)
    s.cc("[Muffled banging. He hears nothing.]", dur=2.2)
    s.wait(2.4)
    s.end()

    # ------------------------------------------------------------------ circling the house
    s = P.shot("d_side", label_i=2, label="KITCHEN")
    s.music("panic", gain=0.45, fade=0.1)
    em = s.actor("emb", x=-170, y=1500, scale=1.0, arms="up", eyes="wide", mouth="grimace", sweat=2)
    s.camera(cx=-170, cy=1000, zoom=1.0)
    em.to(0.0, 0.4, "out", hop=20, shiver=0.6)
    em.to(0.5, 0.2, hop=0)
    s.sfx("click", at=0.3)
    s.overlay("label", at=0.3, dur=1.0, text=["LOCKED"], x=540, y=520, size=56, bg="#ff7b54")
    s.wait(1.1)
    em.set(s.t, walk=1, arms="out", shiver=0)
    em.to(s.t, 1.4, "inout", x=580)
    s.camera(dur=1.4, cx=580)
    s.say(em, "I don't care whose house this is. I need that thing back!", style="shout", advance=False)
    s.wait(1.5)
    em.set(s.t, walk=0, arms="up")
    em.to(s.t, 0.4, "out", hop=20, shiver=0.6)
    em.to(s.t + 0.5, 0.2, hop=0)
    s.sfx("click", at=s.t + 0.3)
    s.overlay("label", at=s.t + 0.3, dur=1.0, text=["ALSO LOCKED"], x=540, y=520, size=56, bg="#ff7b54")
    s.wait(1.2)
    em.set(s.t, walk=1, arms="out", shiver=0)
    em.to(s.t, 1.3, "inout", x=1330)
    s.camera(dur=1.3, cx=1330)
    s.wait(1.4)
    # the kitchen window: stuck
    em.set(s.t, walk=0, arms="up")
    em.to(s.t, 0.3, shiver=1.0, sy=1.04)
    s.say(em, "Come on, come on, come on!", mouth="grimace", eyes="squeeze")
    em.to(s.t, 0.3, shiver=0, sy=1.0, arms="wring", rub=1.5, eyes="wide", mouth="wobbly")
    s.sfx("rustle", gain=0.4)
    s.wait(1.0)
    em.to(s.t, 0.2, rub=0, flail=0.7)
    s.wait(0.9)
    em.to(s.t, 0.4, flail=0, arms="down", rot=0.5, y=1540)
    s.wait(0.5)
    em.to(s.t, 0.3, rot=0, y=1500, arms="holdup", hold="rock")
    s.wait(0.6)
    s.think(em, "Am I really doing this? I'm doing this.", icon="!?", sweat=3)
    # smash
    em.to(s.t, 0.15, aRx=0.4, aRy=-0.5)
    s.sfx("glass", at=s.t + 0.15, gain=1.0)
    s.param(at=s.t + 0.15, broken_i=2, shards=1)
    s.overlay("flash", at=s.t + 0.15, dur=0.3, alpha=0.6)
    s.overlay("sfx", at=s.t + 0.15, dur=0.9, text="CRASH!", x=540, y=600, size=140, color="#ff5f87")
    s.camera(at=s.t + 0.15, shake=12)
    s.camera(at=s.t + 0.5, dur=0.3, shake=0)
    s.wait(0.9)
    em.set(s.t, hold=None, tiptoe=1, arms="face", mouth="grimace", eyes="wide", mortified=0.5)
    s.say(em, "I can't believe I just did that. I can't believe I just did that.", speed=1.1)
    em.set(s.t, tiptoe=0)
    # climb in
    em.to(s.t, 0.5, "in", y=1150, x=1330, arms="up")
    em.to(s.t + 0.5, 0.4, "in", rot=1.5, y=1080, x=1400)
    em.set(s.t + 0.9, visible=0)
    s.sfx("rustle", at=s.t + 0.4, gain=0.7)
    s.wait(1.0)
    s.end()

    # ------------------------------------------------------------------ the kitchen: a heap, then a dog
    s = P.shot("d_kitchen", shadow=-1)
    s.music(None, fade=0.2)
    em = s.actor("emb", x=-260, y=820, scale=0.9, rot=1.5, arms="out", eyes="squeeze", mouth="scream")
    imp = s.actor("imp", x=420, y=KITCHEN_FLOOR, scale=0.85, wall=0, look=-1, looky=0.2, pant=0)
    s.camera(cx=-120, cy=1150, zoom=1.35)
    em.to(0, 0.45, "in", y=1530, x=-180, rot=1.6)
    s.sfx("thud", at=0.45, gain=1.0)
    s.overlay("sfx", at=0.45, dur=0.8, text="THUD", x=380, y=900, size=120, color="#26244a")
    s.camera(at=0.45, shake=10)
    s.camera(at=0.7, dur=0.2, shake=0)
    s.wait(1.2)
    # he looks up... the dog is staring at him
    em.to(s.t, 0.4, rot=1.2, eyes="open", mouth="flat", look=1)
    s.camera(dur=0.8, cx=150, cy=1100, zoom=1.2)
    s.wait(0.9)
    em.to(s.t, 0.2, eyes="wide", mouth="o", rot=0.5, y=1500)
    s.sfx("dun", gain=0.6)
    s.wait(0.4)
    em.to(s.t, 0.2, arms="peek", peek=0.3)
    s.think(em, "Oh my God. It's going to eat me.", icon="X_X")
    em.to(s.t, 0.3, peek=1.0, look=1)
    imp.to(s.t, 0.01, wall=1.0, pant=1.0)
    s.sfx("pant", gain=0.6)
    s.camera(dur=0.5, cx=360, cy=1180, zoom=2.0)
    s.cc("[The dumbest grin in the world]", dur=2.0)
    s.wait(2.4)
    s.end()

    # tiptoe past the tripwire
    s = P.shot("d_kitchen", shadow=-1)
    s.music("sneak", gain=0.55, fade=0.2)
    imp = s.actor("imp", x=420, y=KITCHEN_FLOOR, scale=0.85, wall=1, pant=1)
    em = s.actor("emb", x=-120, y=KITCHEN_FLOOR, scale=0.9, tiptoe=1, arms="wring", eyes="wide",
                 mouth="grimace", sweat=1, look=1, z=1)
    s.camera(cx=300, cy=1100, zoom=1.15)
    s.sfx("pant", gain=0.45)
    s.sfx("tiptoe", gain=0.6)
    em.to(0, 3.2, "lin", x=780)
    s.overlay("label", at=0.5, dur=2.6, text=["IMPULSIVITY", "STATUS: ARMED"], x=300, y=560, size=46,
              bg="#ff7b54")
    s.wait(1.4)
    s.think(em, "Don't move. Don't breathe. One wrong move and it goes off.", icon="!!")
    em.set(s.t, tiptoe=0)
    s.end()

    s = P.shot("d_kitchen", shadow=-1, drawer_i=3, plate_up_i=1)
    imp = s.actor("imp", x=420, y=KITCHEN_FLOOR, scale=0.85, wall=1, pant=1)
    em = s.actor("emb", x=200, y=KITCHEN_FLOOR, scale=0.9, arms="reach", eyes="open", mouth="grimace", sweat=1,
                 look=0.8, z=1)
    s.camera(cx=230, cy=1100, zoom=1.2)
    s.sfx("pant", gain=0.4)
    # under a plate
    s.param(at=0.2, dur=0.4, plate_up=1)
    em.to(0.6, 0.2, look=1.0)
    s.param(at=1.0, dur=0.3, plate_up=0)
    s.sfx("click", at=1.3, gain=0.5)
    # a drawer
    em.to(1.4, 0.5, x=-10, arms="grab", look=-0.3)
    s.param(at=1.9, dur=0.3, drawer=1)
    s.sfx("rustle", at=1.9, gain=0.4)
    em.to(2.4, 0.2, look=1.0)
    s.param(at=2.8, dur=0.3, drawer=0)
    # under the table
    em.to(3.1, 0.5, x=430, rot=0.9, y=KITCHEN_FLOOR + 40, arms="crawl")
    s.wait(3.8)
    s.say(em, "Here, little guy. Please, little guy.", style="whisper")
    em.to(s.t, 0.4, rot=0, y=KITCHEN_FLOOR, x=300, arms="wring", look=1)
    s.wait(0.4)
    s.end()

    s = P.shot("d_kitchen", shadow=-1)
    imp = s.actor("imp", x=420, y=KITCHEN_FLOOR, scale=0.85, wall=1, pant=1)
    s.camera(cx=420, cy=1260, zoom=2.4)
    s.sfx("pant", gain=0.6)
    s.cc("[Not looking at him. Not looking at anything.]", dur=2.0)
    s.wait(2.0)
    s.end()

    # something climbs the stairs
    s = P.shot("d_kitchen", shadow=0.0)
    s.music(None, fade=0.4)
    s.camera(cx=900, cy=1050, zoom=1.0)
    s.camera(dur=1.2, cx=1180, cy=900, zoom=1.05)
    s.param(at=0.6, dur=2.6, ease="lin", shadow=1.0)
    s.sfx("stairscratch", at=0.5, gain=0.9)
    s.sfx("heartbeat", at=0.8, gain=0.5)
    s.cc("[Scratching. Something is climbing the stairs.]", at=0.6, dur=2.6)
    s.wait(3.3)
    s.end()

    s = P.shot("d_room", chair=1, tv=1)
    s.music("lofi_muffled", gain=0.6, fade=0.1)
    td = s.actor("tired", x=540, y=CHAIR_Y, scale=1.1, sit=1, arms="hold2", hold="controller", eyes="closed",
                 mouth="smile", phones=1, music=1)
    hop_loop(td, 0, 3, 0.75, 8)
    s.camera(cx=540, cy=1000, zoom=2.0)
    s.wait(1.8)
    s.end()

    # up the stairs on all fours
    s = P.shot("d_kitchen", shadow=-1)
    s.music("panic", gain=0.4, fade=0.05)
    bx, by = STAIR_BOTTOM
    tx, ty = STAIR_TOP
    em = s.actor("emb", x=bx - 60, y=by + 40, scale=0.75, rot=0.75, arms="crawl", walk=1, eyes="wide",
                 mouth="grimace", sweat=2)
    th = s.actor("thing", x=tx + 200, y=ty + 4, scale=0.6, k=1.0, z=-1)
    s.camera(cx=1150, cy=950, zoom=1.05)
    em.to(0, 1.8, "lin", x=tx - 60, y=ty + 30)
    s.sfx("tiptoe", gain=0.9)
    s.sfx("tiptoe", at=1.0, gain=0.9)
    th.to(1.6, 0.4, sy=0.3, y=ty - 6)
    th.set(2.0, visible=0)
    em.set(1.8, walk=0, rot=0.2)
    s.camera(at=1.6, dur=0.5, cx=tx + 100, cy=ty - 150, zoom=1.6)
    s.wait(2.0)
    s.say(em, "There you are!", style="whisper", eyes="wide", mouth="o")
    s.end()

    # ------------------------------------------------------------------ bursting in
    s = P.shot("d_room", chair=1, tv=1, door=0)
    s.music(None, fade=0.05)
    td = s.actor("tired", x=540, y=CHAIR_Y, scale=1.1, sit=1, arms="hold2", hold="controller", eyes="closed",
                 mouth="smile", phones=1, music=1)
    em = s.actor("emb", x=985, y=1420, scale=0.92, arms="out", eyes="wide", mouth="o", z=1)
    s.camera(cx=760, cy=1000, zoom=1.25)
    s.param(at=0.0, dur=0.15, door=1)
    s.sfx("doorslam", gain=0.9)
    s.wait(0.5)
    # struck by lightning
    em.set(s.t, mortified=1.0, eyes="wide", mouth="grimace", shiver=0.8, arms="up")
    s.sfx("zap", gain=0.9)
    s.overlay("flash", dur=0.35, alpha=0.8, color="#fff3a0")
    s.overlay("sfx", dur=1.0, text="ZAP!", x=820, y=560, size=130, color="#fff3a0")
    s.wait(0.6)
    em.set(s.t, shiver=0, bob=0, autoblink=0)
    s.cc("[Embarrassment has stopped responding]", dur=2.0)
    s.wait(2.2)
    # ...he can't hear me
    em.to(s.t, 0.3, look=-1, eyes="open", mouth="flat")
    s.think(em, "Wait. Headphones. He can't hear me. Okay. Okay.", icon="phew")
    em.to(s.t, 0.5, mortified=0.4, arms="wring")
    em.set(s.t, tiptoe=1)
    em.to(s.t, 1.3, "lin", x=800)
    s.sfx("tiptoe", gain=0.5)
    s.wait(1.3)
    em.set(s.t, tiptoe=0)
    s.end()

    # rummaging + the reveal
    s = P.shot("d_room", tv=1, door=1, closet=1, clothes=1, chair=1)
    s.music("sneak", gain=0.5, fade=0.1)
    em = s.actor("emb", x=800, y=ROOM_FLOOR - 40, scale=0.92, arms="up", flail=0.5, eyes="wide", mouth="grimace",
                 mortified=0.4, z=1)
    td = s.actor("tired", x=640, y=ROOM_FLOOR - 70, scale=1.12, arms="cross", eyes="squint", mouth="flat", phones=0,
                 visible=0, z=0)
    s.camera(cx=800, cy=1150, zoom=2.1)
    s.sfx("rustle", gain=0.6)
    s.say(em, "Come on, come on. Where are you?", style="whisper")
    s.sfx("rustle", gain=0.6)
    td.set(s.t, visible=1)
    s.camera(dur=0.6, cx=700, cy=1080, zoom=1.15)
    s.music(None, fade=0.1)
    s.sfx("dun", at=s.t + 0.5, gain=0.8)
    s.wait(1.6)
    # tap tap
    td.to(s.t, 0.3, arms="reach")
    s.sfx("tap", at=s.t + 0.3, gain=1.0)
    s.sfx("tap", at=s.t + 0.5, gain=1.0)
    s.wait(0.6)
    em.set(s.t, flail=0, arms="up", eyes="wide", mouth="scream", mortified=1.0)
    em.to(s.t, 0.25, "out", hop=650)
    s.sfx("boing2", gain=0.7)
    s.wait(0.25)
    s.end()

    s = P.shot("d_room", tv=1, door=1, closet=1, chair=1)
    td = s.actor("tired", x=640, y=ROOM_FLOOR - 70, scale=1.12, arms="cross", eyes="half", mouth="flat", phones=0)
    s.camera(cx=640, cy=1000, zoom=2.3)
    td.to(0, 0.2, looky=-1, look=0.4)
    s.sfx("impact", at=0.2, gain=1.0)
    s.param(at=0.2, crack=1, crack_x=820, dust=1)
    s.camera(at=0.2, shake=14)
    s.camera(at=0.5, dur=0.2, shake=0)
    s.wait(0.6)
    td.to(s.t, 0.15, looky=1, look=0.4)
    s.sfx("thud", at=s.t + 0.15, gain=1.0)
    s.camera(at=s.t + 0.15, shake=8)
    s.camera(at=s.t + 0.35, dur=0.2, shake=0)
    s.wait(0.9)
    s.end()

    s = P.shot("d_room", tv=1, door=1, closet=1, chair=1, crack=1, crack_x=820, dust=0.6)
    td = s.actor("tired", x=640, y=ROOM_FLOOR - 70, scale=1.12, arms="cross", eyes="half", mouth="flat", phones=0,
                 tap=1)
    em = s.actor("emb", x=820, y=ROOM_FLOOR + 140, scale=0.92, sit=1, eyes="spiral", mouth="wobbly", dazed=1,
                 mortified=0.8, z=1)
    s.camera(cx=730, cy=1150, zoom=1.35)
    s.sfx("tweet", gain=0.7)
    for k in range(6):
        s.sfx("tap", at=0.2 + k * 0.35, gain=0.35)
    s.cc("[Tap. Tap. Tap.]", dur=2.0)
    s.wait(2.2)
    em.set(s.t, dazed=0, eyes="open", mouth="grimace")
    s.say(em, "I... uh... see, the thing is...", look=-0.6, gest=1.0)
    s.end()

    # ------------------------------------------------------------------ the sweater
    s = P.shot("d_room", tv=1, door=1, closet=1, chair=1, crack=1, crack_x=820, thing_desk=1)
    td = s.actor("tired", x=640, y=ROOM_FLOOR - 70, scale=1.12, arms="cross", eyes="half", mouth="flat", phones=0)
    em = s.actor("emb", x=820, y=ROOM_FLOOR + 140, scale=0.92, sit=1, eyes="open", mouth="grimace", mortified=0.6,
                 look=-1, z=1)
    s.camera(cx=600, cy=1150, zoom=1.2)
    s.wait(0.4)
    em.to(s.t, 0.2, eyes="wide", mouth="o")
    s.wait(0.5)
    # zip!
    em.set(s.t, visible=0)
    s.sfx("zip", gain=0.8)
    s.overlay("lines", at=s.t, dur=0.4, x=450, y=1000, color="#ff6b8f")
    s.param(at=s.t + 0.15, thing_desk=0, sweater=1, wiggle=0.3)
    em.set(s.t + 0.15, visible=1, x=420, y=ROOM_FLOOR - 20, sit=0, arms="lean", eyes="open", mouth="grimace",
           look=-0.6, facing=-1)
    s.wait(0.5)
    s.say(em, "Yeah, so... umm... how's everything? I mean... uhh...", gest=0.6, sweat=2)
    s.end()

    s = P.shot("d_room", tv=1, door=1, closet=1, chair=1, crack=1, crack_x=820, sweater=1, wiggle=0.3)
    td = s.actor("tired", x=640, y=ROOM_FLOOR - 70, scale=1.12, arms="cross", eyes="half", mouth="flat", phones=0)
    s.camera(cx=640, cy=1000, zoom=2.2)
    td.to(0.2, 0.3, eyes="roll", looky=-1)
    td.to(0.9, 0.3, eyes="half", looky=0, arms="present", roll=1)
    s.cc("[Go on.]", at=0.9, dur=1.6)
    s.wait(2.3)
    td.set(s.t, roll=0, arms="cross")
    s.end()

    # ------------------------------------------------------------------ "how's that new research job?"
    s = P.shot("d_room", tv=1, door=1, closet=1, chair=1, crack=1, crack_x=820, sweater=1, wiggle=0.3)
    td = s.actor("tired", x=700, y=ROOM_FLOOR - 70, scale=1.12, arms="cross", eyes="half", mouth="flat", phones=0)
    em = s.actor("emb", x=420, y=ROOM_FLOOR - 20, scale=0.92, arms="lean", eyes="open", mouth="grimace",
                 mortified=0.4, look=-0.6, z=1, facing=-1)
    s.camera(cx=560, cy=1080, zoom=1.35)
    s.say(td, "So. How's that new research job going?", look=-0.8)
    em.to(s.t - 0.4, 0.2, eyes="wide", mouth="o", mortified=0.9)
    s.sfx("dun", at=s.t - 0.3, gain=0.5)
    s.wait(0.5)
    s.say(em, "Oh! Yeah. It's good. I think. Yeah. No, wait. It's good.", mouth="grimace", gest=1.0)
    s.say(em, "I was just walking by, so I tried to knock, but I didn't hear anyone, so I let myself in!",
          arms="guns", mouth="grin", eyes="open", speed=1.08, mortified=0.6, sweat=2)
    # the sweater moves
    s.param(wiggle=2.0)
    s.sfx("rustle", gain=0.8)
    s.sfx("chitter", gain=0.5)
    em.to(s.t, 0.12, aRx=-0.4, aRy=0.9, aLx=-0.3, aLy=1.0, eyes="wide", mouth="o")
    em.to(s.t + 0.15, 0.12, aRx=0.9, aRy=0.6, shiver=0.8)
    em.to(s.t + 0.3, 0.12, aRx=-0.5, aRy=0.4)
    s.wait(1.0)
    s.param(wiggle=0.6)
    em.set(s.t, shiver=0.3, arms="lean", mortified=1.0)
    s.say(em, "Please don't tell anyone. Please. I want this job. Please. I'm sorry. Please.", eyes="sad",
          brow=1, mouth="wobbly", tears=0.6, speed=1.0, pitch=1.04)
    td.to(s.t, 0.1, blink=1)
    td.to(s.t + 0.15, 0.1, blink=0)
    s.wait(1.0)
    s.end()

    # ------------------------------------------------------------------ backing out... into a closed door
    s = P.shot("d_room", tv=1, door=0.15, closet=1, chair=1, crack=1, crack_x=820, sweater=1, wiggle=0.6)
    td = s.actor("tired", x=700, y=ROOM_FLOOR - 70, scale=1.12, arms="cross", eyes="half", mouth="flat", phones=0)
    em = s.actor("emb", x=420, y=ROOM_FLOOR - 20, scale=0.92, arms="hold2", eyes="wide", mouth="grimace",
                 mortified=0.7, look=0.6, z=1)
    s.camera(cx=640, cy=1080, zoom=1.2)
    # stuff the sweater bundle into the cage
    s.param(at=0.3, sweater=0)
    em.set(0.3, arms="hold", hold="cage", cage_open=0, cage_full=1, rattle=0.6)
    s.sfx("rustle", at=0.2, gain=0.7)
    s.sfx("rattle", at=0.4, gain=0.6)
    s.wait(0.9)
    em.set(s.t, rattle=0.2)
    s.say(em, "So... I'm going to need to go now.", mouth="grin", eyes="open", look=0.8)
    em.set(s.t, walk=0.6)
    em.to(s.t, 1.6, "inout", x=935)
    s.camera(dur=1.6, cx=760)
    s.wait(1.6)
    em.set(s.t, walk=0)
    s.param(dur=0.12, door=0)
    s.sfx("click", at=s.t + 0.1, gain=1.0)
    s.wait(0.3)
    em.to(s.t, 0.2, eyes="wide", mouth="o", look=1)
    s.wait(0.5)
    s.say(em, "Ha. Haha. Whoops.", mouth="grimace", shiver=0.4, look=-0.6)
    td.to(s.t - 0.6, 0.3, eyes="roll", looky=-1)
    td.to(s.t + 0.4, 0.3, eyes="half", looky=0)
    em.set(s.t, shiver=0)
    s.wait(0.6)
    s.end()

    # ------------------------------------------------------------------ Impulsivity bursts in: tug of war
    s = P.shot("d_room", tv=1, door=0, closet=1, chair=1, crack=1, crack_x=820)
    s.music("panic", gain=0.45, fade=0.05)
    td = s.actor("tired", x=300, y=ROOM_FLOOR - 70, scale=1.12, arms="cross", eyes="half", mouth="flat", phones=0)
    em = s.actor("emb", x=880, y=ROOM_FLOOR - 20, scale=0.92, arms="hold", hold="cage", cage_full=1, rattle=0.2,
                 eyes="open", mouth="grimace", mortified=0.6, z=1)
    imp = s.actor("imp", x=1450, y=ROOM_FLOOR + 10, scale=0.8, run=1, wall=1, z=2, facing=-1)
    s.camera(cx=640, cy=1080, zoom=1.15)
    s.param(at=0.1, dur=0.15, door=1)
    s.sfx("doorslam", at=0.1, gain=0.8)
    s.sfx("bark", at=0.25, gain=1.0)
    s.overlay("sfx", at=0.25, dur=0.9, text="BARK! BARK!", x=820, y=640, size=110, color="#f2b134")
    imp.to(0.15, 0.45, "out", x=1000)
    em.to(0.2, 0.3, x=640, eyes="wide", mouth="scream")
    # the dog snatches the cage
    em.set(0.6, hold=None, arms="tug", rot=-0.12)
    imp.set(0.6, run=0, pant=0, mouthful=1, hold="cage", cage_full=1, rattle=0.4, scale=0.85, x=900)
    s.wait(0.9)
    # the tug of war
    s.sfx("growl", gain=0.8)
    s.sfx("rattle", gain=0.7)
    for k in range(6):
        d = 30 if k % 2 == 0 else -30
        em.to(s.t + k * 0.35, 0.35, x=640 + d)
        imp.to(s.t + k * 0.35, 0.35, x=900 + d)
    imp.set(s.t, rattle=1.0)
    s.say(em, "Let go! Let go! That's not a chew toy!", style="shout", advance=False)
    s.cc("[Tug of war]", dur=2.0)
    s.wait(2.1)
    # Tiredness notices something inside the cage
    td.to(s.t, 0.8, x=560, eyes="squint", lean=0.12)
    td.set(s.t, walk=0.5)
    td.set(s.t + 0.8, walk=0)
    s.camera(dur=0.8, cx=760, cy=1220, zoom=1.7)
    s.wait(1.0)
    s.end()

    s = P.shot("d_room", tv=1, door=1, closet=1, chair=1, crack=1, crack_x=820)
    td = s.actor("tired", x=560, y=ROOM_FLOOR - 70, scale=1.12, arms="cross", eyes="squint", mouth="flat",
                 phones=0, lean=0.12)
    em = s.actor("emb", x=640, y=ROOM_FLOOR - 20, scale=0.92, arms="tug", eyes="wide", mouth="scream",
                 mortified=0.6, z=1, rot=-0.12)
    imp = s.actor("imp", x=900, y=ROOM_FLOOR + 10, scale=0.85, wall=1, pant=0, mouthful=1, hold="cage",
                  cage_full=1, rattle=1.0, z=2, facing=-1)
    th = s.actor("thing", x=860, y=1460, scale=0.7, visible=0, z=3)
    s.camera(cx=800, cy=1300, zoom=2.4)
    s.music(None, fade=0.1)
    s.sfx("creak", gain=0.9)
    imp.to(0.2, 0.6, cage_open=1.0, rattle=0)
    s.wait(0.8)
    # it bursts out and bites
    th.set(s.t, visible=1, writhe=1, bitey=1)
    th.to(s.t, 0.25, "out", x=560, y=1160)
    s.sfx("hiss", at=s.t, gain=0.7)
    s.camera(dur=0.25, cx=600, cy=1050, zoom=1.6)
    s.wait(0.3)
    s.sfx("chomp", gain=1.0)
    s.overlay("flash", dur=0.25, alpha=0.7, color="#ff5f87")
    s.overlay("sfx", dur=0.9, text="CHOMP!", x=380, y=700, size=130, color="#ff5f87")
    td.set(s.t, eyes="wide", mouth="scream", arms="up", flail=1.0, lean=0, shiver=0.6)
    imp.set(s.t, cage_full=0)
    s.say(td, "AAAAAAAAAAAH!", style="shout", advance=False, pitch=1.15)
    s.sfx("shriek", at=s.t + 0.1, gain=0.6)
    s.wait(0.6)
    # he runs out the door; the thing drops; back in the cage
    th.to(s.t, 0.3, "in", y=1480, x=700, writhe=0.3, bitey=0)
    td.set(s.t, walk=1.4, shiver=0)
    td.to(s.t, 1.0, "in", x=1500)
    s.camera(dur=0.4, cx=720, cy=1100, zoom=1.2)
    s.wait(0.9)
    imp.set(s.t, hold=None, mouthful=0, pant=1)
    em.set(s.t, arms="hold", hold="cage", cage_full=0, cage_open=1, rot=0)
    em.to(s.t, 0.3, x=700, rot=0.6)
    th.set(s.t + 0.3, visible=0)
    em.set(s.t + 0.3, cage_full=1, cage_open=0, rot=0)
    s.sfx("click", at=s.t + 0.3, gain=1.0)
    s.sfx("rattle", at=s.t + 0.35, gain=0.5)
    s.wait(0.8)
    s.end()

    # ------------------------------------------------------------------ staring contest
    s = P.shot("d_room", tv=1, door=1, closet=1, chair=1, crack=1, crack_x=820)
    em = s.actor("emb", x=420, y=ROOM_FLOOR + 140, scale=0.92, sit=1, arms="hold2", hold="cage", cage_full=1,
                 eyes="open", mouth="flat", mortified=0.5, look=1)
    imp = s.actor("imp", x=760, y=ROOM_FLOOR + 10, scale=0.85, wall=1, pant=1)
    s.camera(cx=590, cy=1220, zoom=1.5)
    s.say("tired", "IT BIT ME! WHY DOES IT ALWAYS HAVE TO BE ME?!", fx="far", advance=False, pre=0.2)
    s.sfx("pant", gain=0.5)
    s.cc("[Tiredness, screaming outside the window]", at=0.2, dur=2.4)
    s.wait(3.2)
    em.to(s.t, 0.4, arms="facepalm", eyes="closed", mouth="frown")
    s.wait(0.4)
    s.say(em, "Oh my God. What do I do?", mouth="frown")
    s.wait(0.5)
    s.end()

    tbc(P, "PART 2: THE RECORDER")
    return P.finalize()
